/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  CurrentUserProfileResponseResponse,
  UsersListResponseResponse,
} from "../../models";

export const getGetCurrentUserProfileResponseMock = (
  overrideResponse: Partial<
    Extract<CurrentUserProfileResponseResponse, object>
  > = {},
): CurrentUserProfileResponseResponse => ({
  user: {
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
    status: faker.helpers.arrayElement([
      "online",
      "meeting",
      "vacation",
      "notDisturb",
      "workAtHome",
      "freeTime",
      "offline",
    ] as const),
  },
  ...overrideResponse,
});

export const getGetUserProfileByEmailResponseMock = (
  overrideResponse: Partial<Extract<UsersListResponseResponse, object>> = {},
): UsersListResponseResponse => ({
  users: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
    status: faker.helpers.arrayElement([
      "online",
      "meeting",
      "vacation",
      "notDisturb",
      "workAtHome",
      "freeTime",
      "offline",
    ] as const),
  })),
  ...overrideResponse,
});

export const getGetCurrentUserProfileMockHandler = (
  overrideResponse?:
    | CurrentUserProfileResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<CurrentUserProfileResponseResponse>
        | CurrentUserProfileResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/users/me",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCurrentUserProfileResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getUpdateCurrentUserProfileMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/users/me",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getDeleteCurrentUserAccountMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/users/me",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetUserProfileByEmailMockHandler = (
  overrideResponse?:
    | UsersListResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersListResponseResponse> | UsersListResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/users/:emailRegex",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUserProfileByEmailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getAddUserToWorkspaceMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/users/:userId/workspaces/:workspaceId",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getRemoveUserFromWorkspaceMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/users/:userId/workspaces/:workspaceId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getUpdateUserRoleInWorkspaceMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/users/:userId/workspaces/:workspaceId/role",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getUserMock = () => [
  getGetCurrentUserProfileMockHandler(),
  getUpdateCurrentUserProfileMockHandler(),
  getDeleteCurrentUserAccountMockHandler(),
  getGetUserProfileByEmailMockHandler(),
  getAddUserToWorkspaceMockHandler(),
  getRemoveUserFromWorkspaceMockHandler(),
  getUpdateUserRoleInWorkspaceMockHandler(),
];
