/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';


/**
 * Add a reaction to a specific message within a channel. The authenticated user will be set as the author of the reaction. Only members of the channel can add reactions to its messages.
 * @summary Add a reaction to a message in a channel
 */
export const AddReactionToChannelMessageParams = zod.object({
  "workspaceId": zod.string().uuid().describe('The ID of the workspace.'),
  "channelId": zod.string().uuid().describe('The unique identifier of the channel.'),
  "messageId": zod.string().uuid().describe('The unique identifier of the message.')
})

export const AddReactionToChannelMessageBody = zod.object({
  "emoji": zod.string().describe('The emoji to add as a reaction. This should be a valid Unicode emoji.')
})

export const AddReactionToChannelMessageResponse = zod.void()

/**
 * Remove an existing reaction from a specific message within a channel. Only the author of the reaction or workspace admins can remove reactions.
 * @summary Remove a reaction from a message in a channel
 */
export const RemoveReactionFromChannelMessageParams = zod.object({
  "workspaceId": zod.string().uuid().describe('The ID of the workspace.'),
  "channelId": zod.string().uuid().describe('The unique identifier of the channel.'),
  "messageId": zod.string().uuid().describe('The unique identifier of the message.'),
  "reactionId": zod.string().uuid().describe('The ID of the reaction.')
})

export const RemoveReactionFromChannelMessageResponse = zod.unknown()

/**
 * Add a reaction to a specific message within a direct chat. The authenticated user will be set as the author of the reaction. Only members of the direct chat can add reactions to its messages.
 * @summary Add a reaction to a message in a direct chat
 */
export const AddReactionToDirectChatMessageParams = zod.object({
  "workspaceId": zod.string().uuid().describe('The ID of the workspace.'),
  "directChatId": zod.string().uuid().describe('The ID of the direct chat.'),
  "messageId": zod.string().uuid().describe('The unique identifier of the message.')
})

export const AddReactionToDirectChatMessageBody = zod.object({
  "emoji": zod.string().describe('The emoji to add as a reaction. This should be a valid Unicode emoji.')
})

export const AddReactionToDirectChatMessageResponse = zod.void()

/**
 * Remove an existing reaction from a specific message within a direct chat. Only the author of the reaction or workspace admins can remove reactions.
 * @summary Remove a reaction from a message in a direct chat
 */
export const RemoveReactionFromDirectChatMessageParams = zod.object({
  "workspaceId": zod.string().uuid().describe('The ID of the workspace.'),
  "directChatId": zod.string().uuid().describe('The ID of the direct chat.'),
  "messageId": zod.string().uuid().describe('The unique identifier of the message.'),
  "reactionId": zod.string().uuid().describe('The ID of the reaction.')
})

export const RemoveReactionFromDirectChatMessageResponse = zod.unknown()

