name: szponcik-dev

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "9090:8080"
    depends_on:
      kafka:
        condition: service_healthy

  backend:
    environment:
      FLASK_DEBUG: "1"
      GOOGLE_CLIENT_ID: "494938514607-19dj1p23gj58cbmsb6sbb0d4eoljmoao.apps.googleusercontent.com"
    volumes:
      - ./backend:/backend
    command: [ "python", "-u", "main.py" ]

  app:
    build:
      dockerfile: Dockerfile-dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules

  openAPI:
    container_name: openAPI
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./shared/openapi/openapi.yaml:/openapi/openapi.yaml:ro
    ports:
      - "5001:8080"