name: szponcik

include:
  - compose.db.yml

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      FLASK_DEBUG: "0"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: baza_danych
      DB_USER: postgres
      DB_PASSWORD: 1234
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    ports:
      - "5000:5000"
    command: [ "gunicorn", "--preload", "-w", "4", "-b", "0.0.0.0:5000", "main:app" ]
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend