name: szponcik-prod

services:
  backend:
    environment:
      FLASK_DEBUG: "0"
    command: [ "gunicorn", "--preload", "-w", "4", "-b", "0.0.0.0:5000", "main:app" ]

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"