/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * Slack-like communicator schemas for Typescript and Python
 * OpenAPI spec version: 0.0.1
 */

export interface GoogleAuthRequest {
  /** Google OAuth token obtained from the client */
  token: string;
}
