/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */

export * from './confirmWorkspacePaymentRequest';
export * from './createPaymentResponse';
export * from './createWorkspaceRequest';
export * from './errorResponse';
export * from './googleAuthRequest';
export * from './loginRequest';
export * from './registerRequest';
export * from './workspace';
