/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * Slack-like communicator schemas for Typescript and Python
 * OpenAPI spec version: 0.0.1
 */

export interface RegisterRequest {
  name: string;
  surname: string;
  email: string;
  password: string;
  /** Optional avatar image file */
  avatar?: Blob;
}
