FROM python:3.14.2-alpine
WORKDIR /backend-worker

COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend .
COPY .env .

CMD ["python", "workspace_consumer.py"]