/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * Slack-like communicator schemas for Typescript and Python
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LoginRequest,
  RegisterRequest
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Register a new user
 */
export type registerUserResponse201 = {
  data: void
  status: 201
}

export type registerUserResponse400 = {
  data: void
  status: 400
}

export type registerUserResponseSuccess = (registerUserResponse201) & {
  headers: Headers;
};
export type registerUserResponseError = (registerUserResponse400) & {
  headers: Headers;
};

export type registerUserResponse = (registerUserResponseSuccess | registerUserResponseError)

export const getRegisterUserUrl = () => {




  return `/auth/register`
}

export const registerUser = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerUserResponse> => {

  const res = await fetch(getRegisterUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerUserResponse
}




export const getRegisterUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = RegisterRequest
    export type RegisterUserMutationError = void

    /**
 * @summary Register a new user
 */
export const useRegisterUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getRegisterUserMutationOptions(options));
    }
    /**
 * @summary Log in a user and obtain an authentication token
 */
export type loginUserResponse200 = {
  data: void
  status: 200
}

export type loginUserResponse400 = {
  data: void
  status: 400
}

export type loginUserResponse401 = {
  data: void
  status: 401
}

export type loginUserResponseSuccess = (loginUserResponse200) & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse400 | loginUserResponse401) & {
  headers: Headers;
};

export type loginUserResponse = (loginUserResponseSuccess | loginUserResponseError)

export const getLoginUserUrl = () => {




  return `/auth/login`
}

export const loginUser = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginUserResponse> => {

  const res = await fetch(getLoginUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginUserResponse
}




export const getLoginUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = LoginRequest
    export type LoginUserMutationError = void

    /**
 * @summary Log in a user and obtain an authentication token
 */
export const useLoginUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginUserMutationOptions(options));
    }
