/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * Slack-like communicator schemas for Typescript and Python
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';


/**
 * @summary Register a new user
 */
export const RegisterUserBody = zod.object({
  "name": zod.string(),
  "surname": zod.string(),
  "email": zod.string().email(),
  "password": zod.string(),
  "avatar": zod.instanceof(File).optional().describe('Optional avatar image file')
})

/**
 * @summary Log in a user and obtain an authentication token
 */
export const LoginUserBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string()
})

/**
 * @summary Authenticate a user using Google OAuth token
 */
export const GoogleAuthBody = zod.object({
  "token": zod.string().describe('Google OAuth token obtained from the client')
})

