/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GoogleAuthRequest,
  LoginRequest,
  RegisterRequest
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type registerUserResponse201 = {
  data: void
  status: 201
}

export type registerUserResponse400 = {
  data: ErrorResponse
  status: 400
}

export type registerUserResponse409 = {
  data: ErrorResponse
  status: 409
}

export type registerUserResponseSuccess = (registerUserResponse201) & {
  headers: Headers;
};
export type registerUserResponseError = (registerUserResponse400 | registerUserResponse409) & {
  headers: Headers;
};

export type registerUserResponse = (registerUserResponseSuccess | registerUserResponseError)

export const getRegisterUserUrl = () => {




  return `/auth/register`
}

/**
 * @summary Register a new user
 */
export const registerUser = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerUserResponse> => {

  const res = await fetch(getRegisterUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as registerUserResponse
}





export const getRegisterUserQueryKey = (registerRequest?: RegisterRequest,) => {
    return [
    'POST', `/auth/register`, registerRequest
    ] as const;
    }


export const getRegisterUserQueryOptions = <TData = Awaited<ReturnType<typeof registerUser>>, TError = ErrorResponse>(registerRequest: RegisterRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof registerUser>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegisterUserQueryKey(registerRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registerUser>>> = ({ signal }) => registerUser(registerRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registerUser>>, TError, TData> & { queryKey: QueryKey }
}

export type RegisterUserQueryResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
export type RegisterUserQueryError = ErrorResponse


/**
 * @summary Register a new user
 */

export function useRegisterUser<TData = Awaited<ReturnType<typeof registerUser>>, TError = ErrorResponse>(
 registerRequest: RegisterRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof registerUser>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getRegisterUserQueryOptions(registerRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type loginUserResponse200 = {
  data: void
  status: 200
}

export type loginUserResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginUserResponse401 = {
  data: ErrorResponse
  status: 401
}

export type loginUserResponseSuccess = (loginUserResponse200) & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse400 | loginUserResponse401) & {
  headers: Headers;
};

export type loginUserResponse = (loginUserResponseSuccess | loginUserResponseError)

export const getLoginUserUrl = () => {




  return `/auth/login`
}

/**
 * @summary Log in a user and obtain an authentication token
 */
export const loginUser = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginUserResponse> => {

  const res = await fetch(getLoginUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as loginUserResponse
}





export const getLoginUserQueryKey = (loginRequest?: LoginRequest,) => {
    return [
    'POST', `/auth/login`, loginRequest
    ] as const;
    }


export const getLoginUserQueryOptions = <TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorResponse>(loginRequest: LoginRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginUserQueryKey(loginRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginUser>>> = ({ signal }) => loginUser(loginRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData> & { queryKey: QueryKey }
}

export type LoginUserQueryResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
export type LoginUserQueryError = ErrorResponse


/**
 * @summary Log in a user and obtain an authentication token
 */

export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorResponse>(
 loginRequest: LoginRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLoginUserQueryOptions(loginRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type googleAuthResponse200 = {
  data: void
  status: 200
}

export type googleAuthResponse400 = {
  data: ErrorResponse
  status: 400
}

export type googleAuthResponse401 = {
  data: ErrorResponse
  status: 401
}

export type googleAuthResponseSuccess = (googleAuthResponse200) & {
  headers: Headers;
};
export type googleAuthResponseError = (googleAuthResponse400 | googleAuthResponse401) & {
  headers: Headers;
};

export type googleAuthResponse = (googleAuthResponseSuccess | googleAuthResponseError)

export const getGoogleAuthUrl = () => {




  return `/auth/google`
}

/**
 * @summary Authenticate a user using Google OAuth token
 */
export const googleAuth = async (googleAuthRequest: GoogleAuthRequest, options?: RequestInit): Promise<googleAuthResponse> => {

  const res = await fetch(getGoogleAuthUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(googleAuthRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: googleAuthResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as googleAuthResponse
}





export const getGoogleAuthQueryKey = (googleAuthRequest?: GoogleAuthRequest,) => {
    return [
    'POST', `/auth/google`, googleAuthRequest
    ] as const;
    }


export const getGoogleAuthQueryOptions = <TData = Awaited<ReturnType<typeof googleAuth>>, TError = ErrorResponse>(googleAuthRequest: GoogleAuthRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleAuthQueryKey(googleAuthRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleAuth>>> = ({ signal }) => googleAuth(googleAuthRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData> & { queryKey: QueryKey }
}

export type GoogleAuthQueryResult = NonNullable<Awaited<ReturnType<typeof googleAuth>>>
export type GoogleAuthQueryError = ErrorResponse


/**
 * @summary Authenticate a user using Google OAuth token
 */

export function useGoogleAuth<TData = Awaited<ReturnType<typeof googleAuth>>, TError = ErrorResponse>(
 googleAuthRequest: GoogleAuthRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGoogleAuthQueryOptions(googleAuthRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






