/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type { MessageListResponse } from "../../models";

export const getListChannelMessagesResponseMock = (
  overrideResponse: Partial<Extract<MessageListResponse, object>> = {},
): MessageListResponse => ({
  messages: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    content: faker.string.alpha({ length: { min: 10, max: 20 } }),
    sender: {
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
      email: faker.string.alpha({ length: { min: 10, max: 20 } }),
      avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
      status: faker.helpers.arrayElement([
        "online",
        "meeting",
        "vacations",
        "notDisturb",
        "workAtHome",
        "freeTime",
        "offline",
      ] as const),
      workspaceRole: faker.helpers.arrayElement([
        faker.helpers.arrayElement(["owner", "admin", "member"] as const),
        undefined,
      ]),
    },
    timestamp: faker.date.past().toISOString().slice(0, 19) + "Z",
    attachments: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        filename: faker.string.alpha({ length: { min: 10, max: 20 } }),
        url: faker.string.alpha({ length: { min: 10, max: 20 } }),
        size: faker.number.int(),
      })),
      undefined,
    ]),
    reactions: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        emoji: faker.string.alpha({ length: { min: 10, max: 20 } }),
        user: {
          id: faker.string.alpha({ length: { min: 10, max: 20 } }),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
          email: faker.string.alpha({ length: { min: 10, max: 20 } }),
          avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
          status: faker.helpers.arrayElement([
            "online",
            "meeting",
            "vacations",
            "notDisturb",
            "workAtHome",
            "freeTime",
            "offline",
          ] as const),
          workspaceRole: faker.helpers.arrayElement([
            faker.helpers.arrayElement(["owner", "admin", "member"] as const),
            undefined,
          ]),
        },
      })),
      undefined,
    ]),
    isEdited: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  })),
  ...overrideResponse,
});

export const getListDirectChatMessagesResponseMock = (
  overrideResponse: Partial<Extract<MessageListResponse, object>> = {},
): MessageListResponse => ({
  messages: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    content: faker.string.alpha({ length: { min: 10, max: 20 } }),
    sender: {
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
      email: faker.string.alpha({ length: { min: 10, max: 20 } }),
      avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
      status: faker.helpers.arrayElement([
        "online",
        "meeting",
        "vacations",
        "notDisturb",
        "workAtHome",
        "freeTime",
        "offline",
      ] as const),
      workspaceRole: faker.helpers.arrayElement([
        faker.helpers.arrayElement(["owner", "admin", "member"] as const),
        undefined,
      ]),
    },
    timestamp: faker.date.past().toISOString().slice(0, 19) + "Z",
    attachments: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        filename: faker.string.alpha({ length: { min: 10, max: 20 } }),
        url: faker.string.alpha({ length: { min: 10, max: 20 } }),
        size: faker.number.int(),
      })),
      undefined,
    ]),
    reactions: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        emoji: faker.string.alpha({ length: { min: 10, max: 20 } }),
        user: {
          id: faker.string.alpha({ length: { min: 10, max: 20 } }),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
          email: faker.string.alpha({ length: { min: 10, max: 20 } }),
          avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
          status: faker.helpers.arrayElement([
            "online",
            "meeting",
            "vacations",
            "notDisturb",
            "workAtHome",
            "freeTime",
            "offline",
          ] as const),
          workspaceRole: faker.helpers.arrayElement([
            faker.helpers.arrayElement(["owner", "admin", "member"] as const),
            undefined,
          ]),
        },
      })),
      undefined,
    ]),
    isEdited: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  })),
  ...overrideResponse,
});
