/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Create a new message within the specified channel. The authenticated user will be set as the author of the message. Only members of the channel can create messages.
 * @summary Create a new message in a channel
 */
export const CreateChannelMessageParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
});

export const CreateChannelMessageBody = zod.object({
  content: zod.string().describe("The content of the message."),
  attachments: zod
    .array(zod.instanceof(File))
    .describe("A list of attachment files for the message."),
});

export const CreateChannelMessageResponse = zod.void();

/**
 * Retrieve a paginated list of messages within the specified channel. Only members of the channel can view its messages.
 * @summary List messages in a channel with pagination
 */
export const listChannelMessagesPathPageDefault = 1;

export const listChannelMessagesPathPageSizeDefault = 20;
export const listChannelMessagesPathPageSizeMax = 50;

export const ListChannelMessagesParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
  page: zod
    .number()
    .min(1)
    .default(listChannelMessagesPathPageDefault)
    .describe("The page number to retrieve."),
  pageSize: zod
    .number()
    .min(1)
    .max(listChannelMessagesPathPageSizeMax)
    .default(listChannelMessagesPathPageSizeDefault)
    .describe("The number of items to retrieve per page."),
});

export const ListChannelMessagesResponse = zod.object({
  messages: zod
    .array(
      zod.object({
        id: zod.string().describe("Unique identifier for the message."),
        content: zod.string().describe("The content of the message."),
        sender: zod
          .object({
            id: zod.string().describe("Unique identifier for the user"),
            name: zod.string().describe("Name of the user"),
            surname: zod.string().describe("Surname of the user"),
            email: zod.string().describe("Email address of the user"),
            avatarUrl: zod.string().describe("URL of the user's avatar image"),
            status: zod.enum([
              "online",
              "meeting",
              "vacations",
              "notDisturb",
              "workAtHome",
              "freeTime",
              "offline",
            ]),
            workspaceRole: zod
              .enum(["owner", "admin", "member"])
              .optional()
              .describe(
                "The user's role within the workspace (only set in workspace member listings).",
              ),
          })
          .describe("The user who sent the message."),
        timestamp: zod
          .string()
          .datetime({ offset: true })
          .describe("The time when the message was sent."),
        attachments: zod
          .array(
            zod.object({
              id: zod
                .string()
                .describe("Unique identifier for the attachment."),
              filename: zod.string().describe("Name of the attached file."),
              url: zod
                .string()
                .describe("Relative URL where the attachment can be accessed."),
              size: zod
                .number()
                .describe("Size of the attached file in bytes."),
            }),
          )
          .optional()
          .describe("List of attachments included in the message."),
        reactions: zod
          .array(
            zod.object({
              id: zod
                .string()
                .describe("The unique identifier of the reaction."),
              emoji: zod.string().describe("The emoji used in the reaction."),
              user: zod
                .object({
                  id: zod.string().describe("Unique identifier for the user"),
                  name: zod.string().describe("Name of the user"),
                  surname: zod.string().describe("Surname of the user"),
                  email: zod.string().describe("Email address of the user"),
                  avatarUrl: zod
                    .string()
                    .describe("URL of the user's avatar image"),
                  status: zod.enum([
                    "online",
                    "meeting",
                    "vacations",
                    "notDisturb",
                    "workAtHome",
                    "freeTime",
                    "offline",
                  ]),
                  workspaceRole: zod
                    .enum(["owner", "admin", "member"])
                    .optional()
                    .describe(
                      "The user's role within the workspace (only set in workspace member listings).",
                    ),
                })
                .describe("The user who made the reaction."),
            }),
          )
          .optional()
          .describe("List of reactions to the message."),
        isEdited: zod
          .boolean()
          .optional()
          .describe("Indicates whether the message has been edited."),
      }),
    )
    .describe("List of messages."),
});

/**
 * Update the content of an existing message within the specified channel. Only the author of the message can update it.
 * @summary Update a message in a channel
 */
export const UpdateChannelMessageParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
  messageId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the message."),
});

export const UpdateChannelMessageBody = zod.object({
  content: zod.string().describe("The updated content of the message."),
});

export const UpdateChannelMessageResponse = zod.unknown();

/**
 * Delete an existing message from the specified channel. Only the author of the message or workspace admins can delete messages.
 * @summary Delete a message from a channel
 */
export const DeleteChannelMessageParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
  messageId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the message."),
});

export const DeleteChannelMessageResponse = zod.unknown();

/**
 * Create a new message within the specified direct chat. The authenticated user will be set as the author of the message. Only members of the direct chat can create messages.
 * @summary Create a new message in a direct chat
 */
export const CreateDirectChatMessageParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  directChatId: zod.string().uuid().describe("The ID of the direct chat."),
});

export const CreateDirectChatMessageBody = zod.object({
  content: zod.string().describe("The content of the message."),
  attachments: zod
    .array(zod.instanceof(File))
    .describe("A list of attachment files for the message."),
});

export const CreateDirectChatMessageResponse = zod.void();

/**
 * Retrieve a paginated list of messages within the specified direct chat. Only members of the direct chat can view its messages.
 * @summary List messages in a direct chat with pagination
 */
export const listDirectChatMessagesPathPageDefault = 1;

export const listDirectChatMessagesPathPageSizeDefault = 20;
export const listDirectChatMessagesPathPageSizeMax = 50;

export const ListDirectChatMessagesParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  directChatId: zod.string().uuid().describe("The ID of the direct chat."),
  page: zod
    .number()
    .min(1)
    .default(listDirectChatMessagesPathPageDefault)
    .describe("The page number to retrieve."),
  pageSize: zod
    .number()
    .min(1)
    .max(listDirectChatMessagesPathPageSizeMax)
    .default(listDirectChatMessagesPathPageSizeDefault)
    .describe("The number of items to retrieve per page."),
});

export const ListDirectChatMessagesResponse = zod.object({
  messages: zod
    .array(
      zod.object({
        id: zod.string().describe("Unique identifier for the message."),
        content: zod.string().describe("The content of the message."),
        sender: zod
          .object({
            id: zod.string().describe("Unique identifier for the user"),
            name: zod.string().describe("Name of the user"),
            surname: zod.string().describe("Surname of the user"),
            email: zod.string().describe("Email address of the user"),
            avatarUrl: zod.string().describe("URL of the user's avatar image"),
            status: zod.enum([
              "online",
              "meeting",
              "vacations",
              "notDisturb",
              "workAtHome",
              "freeTime",
              "offline",
            ]),
            workspaceRole: zod
              .enum(["owner", "admin", "member"])
              .optional()
              .describe(
                "The user's role within the workspace (only set in workspace member listings).",
              ),
          })
          .describe("The user who sent the message."),
        timestamp: zod
          .string()
          .datetime({ offset: true })
          .describe("The time when the message was sent."),
        attachments: zod
          .array(
            zod.object({
              id: zod
                .string()
                .describe("Unique identifier for the attachment."),
              filename: zod.string().describe("Name of the attached file."),
              url: zod
                .string()
                .describe("Relative URL where the attachment can be accessed."),
              size: zod
                .number()
                .describe("Size of the attached file in bytes."),
            }),
          )
          .optional()
          .describe("List of attachments included in the message."),
        reactions: zod
          .array(
            zod.object({
              id: zod
                .string()
                .describe("The unique identifier of the reaction."),
              emoji: zod.string().describe("The emoji used in the reaction."),
              user: zod
                .object({
                  id: zod.string().describe("Unique identifier for the user"),
                  name: zod.string().describe("Name of the user"),
                  surname: zod.string().describe("Surname of the user"),
                  email: zod.string().describe("Email address of the user"),
                  avatarUrl: zod
                    .string()
                    .describe("URL of the user's avatar image"),
                  status: zod.enum([
                    "online",
                    "meeting",
                    "vacations",
                    "notDisturb",
                    "workAtHome",
                    "freeTime",
                    "offline",
                  ]),
                  workspaceRole: zod
                    .enum(["owner", "admin", "member"])
                    .optional()
                    .describe(
                      "The user's role within the workspace (only set in workspace member listings).",
                    ),
                })
                .describe("The user who made the reaction."),
            }),
          )
          .optional()
          .describe("List of reactions to the message."),
        isEdited: zod
          .boolean()
          .optional()
          .describe("Indicates whether the message has been edited."),
      }),
    )
    .describe("List of messages."),
});

/**
 * Update the content of an existing message within the specified direct chat. Only the author of the message can update it.
 * @summary Update a message in a direct chat
 */
export const UpdateDirectChatMessageParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  directChatId: zod.string().uuid().describe("The ID of the direct chat."),
  messageId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the message."),
});

export const UpdateDirectChatMessageBody = zod.object({
  content: zod.string().describe("The updated content of the message."),
});

export const UpdateDirectChatMessageResponse = zod.unknown();

/**
 * Delete an existing message from the specified direct chat. Only the author of the message or workspace admins can delete messages.
 * @summary Delete a message from a direct chat
 */
export const DeleteDirectChatMessageParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  directChatId: zod.string().uuid().describe("The ID of the direct chat."),
  messageId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the message."),
});

export const DeleteDirectChatMessageResponse = zod.unknown();
