/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  N400Response,
  N401Response,
  N403Response,
  N404Response
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type deleteAttachmentFromChannelMessageResponse200 = {
  data: void
  status: 200
}

export type deleteAttachmentFromChannelMessageResponse400 = {
  data: N400Response
  status: 400
}

export type deleteAttachmentFromChannelMessageResponse401 = {
  data: N401Response
  status: 401
}

export type deleteAttachmentFromChannelMessageResponse403 = {
  data: N403Response
  status: 403
}

export type deleteAttachmentFromChannelMessageResponse404 = {
  data: N404Response
  status: 404
}

export type deleteAttachmentFromChannelMessageResponseSuccess = (deleteAttachmentFromChannelMessageResponse200) & {
  headers: Headers;
};
export type deleteAttachmentFromChannelMessageResponseError = (deleteAttachmentFromChannelMessageResponse400 | deleteAttachmentFromChannelMessageResponse401 | deleteAttachmentFromChannelMessageResponse403 | deleteAttachmentFromChannelMessageResponse404) & {
  headers: Headers;
};

export type deleteAttachmentFromChannelMessageResponse = (deleteAttachmentFromChannelMessageResponseSuccess | deleteAttachmentFromChannelMessageResponseError)

export const getDeleteAttachmentFromChannelMessageUrl = (workspaceId: string,
    channelId: string,
    messageId: string,
    attachmentId: string,) => {




  return `/workspaces/${workspaceId}/channels/${channelId}/messages/${messageId}/attachments/${attachmentId}`
}

/**
 * Delete an existing attachment from a specific message within a channel. Only the author of the message or workspace admins can delete attachments.
 * @summary Delete an attachment from a message in a channel
 */
export const deleteAttachmentFromChannelMessage = async (workspaceId: string,
    channelId: string,
    messageId: string,
    attachmentId: string, options?: RequestInit): Promise<deleteAttachmentFromChannelMessageResponse> => {

  const res = await fetch(getDeleteAttachmentFromChannelMessageUrl(workspaceId,channelId,messageId,attachmentId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteAttachmentFromChannelMessageResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteAttachmentFromChannelMessageResponse
}




export const getDeleteAttachmentFromChannelMessageMutationOptions = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentFromChannelMessage>>, TError,{workspaceId: string;channelId: string;messageId: string;attachmentId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentFromChannelMessage>>, TError,{workspaceId: string;channelId: string;messageId: string;attachmentId: string}, TContext> => {

const mutationKey = ['deleteAttachmentFromChannelMessage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAttachmentFromChannelMessage>>, {workspaceId: string;channelId: string;messageId: string;attachmentId: string}> = (props) => {
          const {workspaceId,channelId,messageId,attachmentId} = props ?? {};

          return  deleteAttachmentFromChannelMessage(workspaceId,channelId,messageId,attachmentId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAttachmentFromChannelMessageMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAttachmentFromChannelMessage>>>

    export type DeleteAttachmentFromChannelMessageMutationError = N400Response | N401Response | N403Response | N404Response

    /**
 * @summary Delete an attachment from a message in a channel
 */
export const useDeleteAttachmentFromChannelMessage = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentFromChannelMessage>>, TError,{workspaceId: string;channelId: string;messageId: string;attachmentId: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAttachmentFromChannelMessage>>,
        TError,
        {workspaceId: string;channelId: string;messageId: string;attachmentId: string},
        TContext
      > => {
      return useMutation(getDeleteAttachmentFromChannelMessageMutationOptions(options));
    }
