openapi: 3.1.0

info:
  title: Szponcik communicator API
  version: 0.0.1

tags:
  - name: Auth
    description: User authentication and registration

  - name: Workspace
    description: Workspaces management

  - name: Channel
    description: Channels management

  - name: Direct Chat
    description: Direct chats management

  - name: Message
    description: Messages in channels and direct chats management

  - name: User
    description: User profile and settings management

servers:
  - url: http://localhost:5000/api
    description: Local server

components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: cookie
      name: access_token

    RefreshTokenAuth:
      type: apiKey
      in: cookie
      name: refresh_token

security:
  - TokenAuth: [ ]

paths:
  # ----- Auth -----
  /auth/register:
    post:
      operationId: registerUser
      tags: [ Auth ]
      summary: Register a new user
      description: Create a new user account with the provided information. The profile picture is optional and can be uploaded as part of the registration process.
      security: [ ]

      requestBody:
        $ref: 'components/requestBodies/auth.yaml#/RegisterRequest'

      responses:
        '201':
          description: User registered successfully

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '409':
          $ref: 'components/responses/error.yaml#/409'

  /auth/login:
    post:
      operationId: loginUser
      tags: [ Auth ]
      summary: Log in a user and obtain an authentication token
      description: Authenticate a user with their email and password. On successful authentication, sets both access_token and refresh_token cookies for session management.
      security: [ ]

      requestBody:
        $ref: 'components/requestBodies/auth.yaml#/LoginRequest'

      responses:
        '200':
          $ref: 'components/responses/auth.yaml#/LoginResponse'

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'

  /auth/google:
    post:
      operationId: googleAuth
      tags: [ Auth ]
      summary: Authenticate a user using Google OAuth token
      description: Authenticate a user with a Google OAuth token. On successful authentication, sets both access_token and refresh_token cookies for session management.
      security: [ ]

      requestBody:
        $ref: 'components/requestBodies/auth.yaml#/GoogleAuthRequest'

      responses:
        '200':
          $ref: 'components/responses/auth.yaml#/LoginResponse'

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'

  /auth/refresh:
    post:
      operationId: refreshToken
      tags: [ Auth ]
      summary: Refresh the authentication token using the refresh token
      description: Use the refresh token to obtain a new access token. This endpoint requires a valid refresh_token cookie and will set a new access_token cookie on success.
      security:
        - RefreshTokenAuth: [ ]

      responses:
        '200':
          $ref: 'components/responses/auth.yaml#/TokenRefreshResponse'

        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'

  # ----- Workspace -----
  /workspaces:
    post:
      operationId: createWorkspace
      tags: [ Workspace ]
      summary: Create a new workspace
      description: Create a new workspace with the provided name and optional logo. The user creating the workspace will be set as the owner. To create workspace client need complete payment using returned Stripe Payment Intent client secret.
      security:
        - TokenAuth: [ ]

      requestBody:
        $ref: 'components/requestBodies/workspace.yaml#/CreateWorkspaceRequest'

      responses:
        '201':
          $ref: 'components/responses/payment.yaml#/CreatePaymentResponse'

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'

    get:
      operationId: listWorkspaces
      tags: [ Workspace ]
      summary: List all workspaces the user is a member of
      description: Retrieve a list of all workspaces that the authenticated user is a member of, including their roles within each workspace.
      security:
        - TokenAuth: [ ]

      responses:
        '200':
          $ref: 'components/responses/workspace.yaml#/WorkspaceListResponse'

        '401':
          $ref: 'components/responses/error.yaml#/401'

  /workspaces/accept-payment:
    post:
      operationId: acceptWorkspacePayment
      tags: [ Workspace ]
      summary: Accept payment for workspace creation
      description: Confirm the Stripe Payment Intent for workspace creation. This endpoint should be called after the client completes the payment process using the client secret provided in the response of the workspace creation endpoint.
      security:
        - TokenAuth: [ ]

      requestBody:
        $ref: 'components/requestBodies/payment.yaml#/AcceptPaymentRequest'

      responses:
        '200':
          description: Payment accepted and workspace created successfully

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '402':
          $ref: 'components/responses/error.yaml#/402'

  /workspaces/{workspaceId}:
    patch:
      operationId: updateWorkspaceLogo
      tags: [ Workspace ]
      summary: Update workspace logo
      description: Update the logo of an existing workspace. Only the workspace owner can update the logo.
      security:
        - TokenAuth: [ ]
      parameters:
        - $ref: 'components/parameters/workspace.yaml#/WorkspaceIDParameter'

      requestBody:
        $ref: 'components/requestBodies/workspace.yaml#/UpdateWorkspaceLogoRequest'

      responses:
        '200':
          description: Workspace logo updated successfully
        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'
        '404':
          $ref: 'components/responses/error.yaml#/404'

  # ----- Channel -----
  /workspaces/{workspaceId}/channels:
    post:
      operationId: createChannel
      tags: [ Channel ]
      summary: Create a new channel in a workspace
      description: Create a new channel within the specified workspace. The user creating the channel will be added as a member of that channel. Only owners and admins of the workspace can create channels.
      security:
        - TokenAuth: [ ]
      parameters:
        - $ref: 'components/parameters/workspace.yaml#/WorkspaceIDParameter'

      requestBody:
        $ref: 'components/requestBodies/channel.yaml#/CreateChannelRequest'

      responses:
        '201':
          description: Channel created successfully

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'
        '404':
          $ref: 'components/responses/error.yaml#/404'

    get:
      operationId: listChannels
      tags: [ Channel ]
      summary: List all channels in a workspace
      description: Retrieve a list of all channels within the specified workspace.
      security:
        - TokenAuth: [ ]
      parameters:
        - $ref: 'components/parameters/workspace.yaml#/WorkspaceIDParameter'

      responses:
        '200':
          $ref: 'components/responses/channel.yaml#/ChannelListResponse'

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'
        '404':
          $ref: 'components/responses/error.yaml#/404'

  /workspaces/{workspaceId}/channels/{channelId}:
    patch:
      operationId: updateChannelName
      tags: [ Channel ]
      summary: Update the name of a channel
      description: Update the name of an existing channel within the specified workspace. Only owners and admins of the workspace can update channel names.
      security:
        - TokenAuth: [ ]
      parameters:
        - $ref: 'components/parameters/workspace.yaml#/WorkspaceIDParameter'
        - $ref: 'components/parameters/channel.yaml#/ChannelIDParameter'

      requestBody:
        $ref: 'components/requestBodies/channel.yaml#/UpdateChannelNameRequest'

      responses:
        '200':
          description: Channel name updated successfully

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'
        '404':
          $ref: 'components/responses/error.yaml#/404'

    delete:
      operationId: deleteChannel
      tags: [ Channel ]
      summary: Delete a channel from a workspace
      description: Delete an existing channel from the specified workspace. Only owners and admins of the workspace can delete channels.
      security:
        - TokenAuth: [ ]
      parameters:
        - $ref: 'components/parameters/workspace.yaml#/WorkspaceIDParameter'
        - $ref: 'components/parameters/channel.yaml#/ChannelIDParameter'

      responses:
        '200':
          description: Channel deleted successfully

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'
        '404':
          $ref: 'components/responses/error.yaml#/404'

  # ----- Direct Chat -----
  /workspaces/{workspaceId}/direct-chats:
    get:
      operationId: listDirectChats
      tags: [ Direct Chat ]
      summary: List all direct chats in a workspace
      description: Retrieve a list of all direct chats that the authenticated user is a part of within the specified workspace.
      security:
        - TokenAuth: [ ]
      parameters:
        - $ref: 'components/parameters/workspace.yaml#/WorkspaceIDParameter'

      responses:
        '200':
          $ref: 'components/responses/directChat.yaml#/DirectChatListResponse'

        '400':
          $ref: 'components/responses/error.yaml#/400'
        '401':
          $ref: 'components/responses/error.yaml#/401'
        '403':
          $ref: 'components/responses/error.yaml#/403'
        '404':
          $ref: 'components/responses/error.yaml#/404'