/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type AcceptPaymentBody = {
  /** ID of the Stripe Payment Intent to confirm */
  paymentIntentId: string;
};
