/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type AddReactionRequestBody = {
  /** The emoji to add as a reaction. This should be a valid Unicode emoji. */
  emoji: string;
};
