/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { Channel } from './channel';

export type ChannelListResponseResponse = {
  channels: Channel[];
};
