/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Channel } from "./channel";

export type ChannelListResponseResponse = {
  channels: Channel[];
};
