/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOutgoingWebhookBodyEventsItem } from "./createOutgoingWebhookBodyEventsItem";
import type { CreateOutgoingWebhookBodyFormat } from "./createOutgoingWebhookBodyFormat";

export type CreateOutgoingWebhookBody = {
  name: string;
  url: string;
  format: CreateOutgoingWebhookBodyFormat;
  events: CreateOutgoingWebhookBodyEventsItem[];
};
