/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type CreateChannelBody = {
  /** The name of the channel */
  name: string;
};
