/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */

export type CreateMessageRequestBody = {
  /** The content of the message. */
  content: string;
  /** A list of attachment files for the message. */
  attachments: Blob[];
};
