/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOutgoingWebhookBodyEventsItem =
  (typeof CreateOutgoingWebhookBodyEventsItem)[keyof typeof CreateOutgoingWebhookBodyEventsItem];

export const CreateOutgoingWebhookBodyEventsItem = {
  messagecreated: "message.created",
  channelcreated: "channel.created",
  memberadded: "member.added",
} as const;
