/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type CreatePaymentResponse = {
  /** Secret key generated by Stripe for processing the payment */
  clientSecret: string;
};
