/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOutgoingWebhookBodyFormat =
  (typeof CreateOutgoingWebhookBodyFormat)[keyof typeof CreateOutgoingWebhookBodyFormat];

export const CreateOutgoingWebhookBodyFormat = {
  native: "native",
  slack: "slack",
  discord: "discord",
} as const;
