/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";

export type CurrentUserProfileResponse = {
  /** The current user's profile information. */
  user: User;
};
