/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type GoogleAuthBody = {
  /** Google OAuth token obtained from the client */
  token: string;
};
