/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export interface IncomingWebhook {
  id: string;
  channelId: string;
  name: string;
  /** Relative URL external services POST to in order to post a message. */
  url: string;
  createdAt?: string;
}
