/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { IncomingWebhook } from "./incomingWebhook";

export type ListIncomingWebhooks200 = {
  webhooks: IncomingWebhook[];
};
