/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Message } from "./message";

export type MessageListResponse = {
  /** List of messages. */
  messages: Message[];
};
