/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { Message } from './message';

export type MessageListResponseResponse = {
  /** List of messages. */
  messages: Message[];
};
