/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { ErrorSchema } from './errorSchema';

/**
 * Bad Request - The request could not be understood or was missing required parameters
 */
export type N400Response = ErrorSchema;
