/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from "./error";

/**
 * Bad Request - The request could not be understood or was missing required parameters
 */
export type N400Response = Error;
