/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from "./error";

/**
 * Unauthorized - Authentication is required and has failed or has not yet been provided
 */
export type N401Response = Error;
