/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { ErrorSchema } from './errorSchema';

/**
 * Payment Required - Payment is required to access the resource
 */
export type N402Response = ErrorSchema;
