/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from "./error";

/**
 * Payment Required - Payment is required to access the resource
 */
export type N402Response = Error;
