/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorSchema } from './errorSchema';

/**
 * Forbidden - The user does not have permission to access the resource
 */
export type N403Response = ErrorSchema;
