/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from "./error";

/**
 * Not Found - The requested resource was not found
 */
export type N404Response = Error;
