/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorSchema } from "./errorSchema";

/**
 * Not Found - The requested resource was not found
 */
export type N404Response = ErrorSchema;
