/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from "./error";

/**
 * Conflict - The request could not be completed due to a conflict with the current state of the resource
 */
export type N409Response = Error;
