/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { ErrorSchema } from './errorSchema';

/**
 * Conflict - The request could not be completed due to a conflict with the current state of the resource
 */
export type N409Response = ErrorSchema;
