/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type OutgoingWebhookEventsItem =
  (typeof OutgoingWebhookEventsItem)[keyof typeof OutgoingWebhookEventsItem];

export const OutgoingWebhookEventsItem = {
  messagecreated: "message.created",
  channelcreated: "channel.created",
  memberadded: "member.added",
} as const;
