/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { OutgoingWebhookEventsItem } from "./outgoingWebhookEventsItem";
import type { OutgoingWebhookFormat } from "./outgoingWebhookFormat";

export interface OutgoingWebhook {
  id: string;
  name: string;
  url: string;
  format: OutgoingWebhookFormat;
  events: OutgoingWebhookEventsItem[];
  isActive: boolean;
  /** HMAC signing secret (returned only when the webhook is created). */
  secret?: string;
  createdAt?: string;
}
