/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { User } from './user';

export interface Reaction {
  /** The unique identifier of the reaction. */
  id: string;
  /** The emoji used in the reaction. */
  emoji: string;
  /** The user who made the reaction. */
  user: User;
}
