/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type RegisterBody = {
  name: string;
  surname: string;
  email: string;
  password: string;
  /** Optional avatar image file */
  avatar?: Blob;
};
