/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */

export type RegisterRequestBody = {
  name: string;
  surname: string;
  email: string;
  password: string;
  /** Optional avatar image file */
  avatar?: Blob;
};
