/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Token refreshed successfully
 */
export type TokenRefreshResponse = void;
