/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */

/**
 * The new role for the user.
 */
export type UpdateUserRoleRequestBodyRole = typeof UpdateUserRoleRequestBodyRole[keyof typeof UpdateUserRoleRequestBodyRole];


export const UpdateUserRoleRequestBodyRole = {
  admin: 'admin',
  member: 'member',
} as const;
