/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserRoleRequestBodyRole } from "./updateUserRoleRequestBodyRole";

export type UpdateUserRoleRequestBody = {
  /** The new role for the user. */
  role: UpdateUserRoleRequestBodyRole;
};
