/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateChannelNameRequestBody = {
  /** The new name of the channel */
  name: string;
};
