/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The user's current status.
 */
export type UpdateCurrentUserProfileRequestBodyStatus = typeof UpdateCurrentUserProfileRequestBodyStatus[keyof typeof UpdateCurrentUserProfileRequestBodyStatus];


export const UpdateCurrentUserProfileRequestBodyStatus = {
  online: 'online',
  meeting: 'meeting',
  vacation: 'vacation',
  notDisturb: 'notDisturb',
  workAtHome: 'workAtHome',
  freeTime: 'freeTime',
  offline: 'offline',
} as const;
