/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The user's current status.
 */
export type UpdateCurrentUserProfileBodyStatus =
  (typeof UpdateCurrentUserProfileBodyStatus)[keyof typeof UpdateCurrentUserProfileBodyStatus];

export const UpdateCurrentUserProfileBodyStatus = {
  online: "online",
  meeting: "meeting",
  vacations: "vacations",
  notDisturb: "notDisturb",
  workAtHome: "workAtHome",
  freeTime: "freeTime",
  offline: "offline",
} as const;
