/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateUserRoleRequestBodyRole } from './updateUserRoleRequestBodyRole';

export type UpdateUserRoleRequestBody = {
  /** The new role for the user. */
  role: UpdateUserRoleRequestBodyRole;
};
