/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserRoleBodyRole } from "./updateUserRoleBodyRole";

export type UpdateUserRoleBody = {
  /** The new role for the user. */
  role: UpdateUserRoleBodyRole;
};
