/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCurrentUserProfileBodyStatus } from "./updateCurrentUserProfileBodyStatus";

export type UpdateCurrentUserProfileBody = {
  /** The user's name. */
  name: string;
  /** The user's surname. */
  surname: string;
  /** The user's email address. */
  email: string;
  /** The user's avatar image file. */
  avatar?: Blob;
  /** The user's current status. */
  status: UpdateCurrentUserProfileBodyStatus;
};
