/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The new role for the user.
 */
export type UpdateUserRoleRequestBodyRole =
  (typeof UpdateUserRoleRequestBodyRole)[keyof typeof UpdateUserRoleRequestBodyRole];

export const UpdateUserRoleRequestBodyRole = {
  admin: "admin",
  member: "member",
} as const;
