/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateCurrentUserProfileRequestBodyStatus } from './updateCurrentUserProfileRequestBodyStatus';

export type UpdateCurrentUserProfileRequestBody = {
  /** The user's name. */
  name: string;
  /** The user's surname. */
  surname: string;
  /** The user's email address. */
  email: string;
  /** The user's avatar image file. */
  avatar?: Blob;
  /** The user's current status. */
  status: UpdateCurrentUserProfileRequestBodyStatus;
};
