/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The user's role within the workspace (only set in workspace member listings).
 */
export type UserWorkspaceRole =
  (typeof UserWorkspaceRole)[keyof typeof UserWorkspaceRole];

export const UserWorkspaceRole = {
  owner: "owner",
  admin: "admin",
  member: "member",
} as const;
