/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export const UserStatus = {
  online: "online",
  meeting: "meeting",
  vacation: "vacation",
  notDisturb: "notDisturb",
  workAtHome: "workAtHome",
  freeTime: "freeTime",
  offline: "offline",
} as const;
