/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import type { Workspace } from "./workspace";

export type WorkspaceListResponse = {
  workspaces: Workspace[];
};
