/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The role of the authenticated user within the workspace
 */
export type WorkspaceUserRole =
  (typeof WorkspaceUserRole)[keyof typeof WorkspaceUserRole];

export const WorkspaceUserRole = {
  owner: "owner",
  admin: "admin",
  member: "member",
} as const;
