/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
  IncomingWebhook,
  ListIncomingWebhooks200,
  ListOutgoingWebhooks200,
  OutgoingWebhook,
} from "../../models";

export const getCreateIncomingWebhookResponseMock = (
  overrideResponse: Partial<Extract<IncomingWebhook, object>> = {},
): IncomingWebhook => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  channelId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getListIncomingWebhooksResponseMock = (
  overrideResponse: Partial<Extract<ListIncomingWebhooks200, object>> = {},
): ListIncomingWebhooks200 => ({
  webhooks: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    channelId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getCreateOutgoingWebhookResponseMock = (
  overrideResponse: Partial<Extract<OutgoingWebhook, object>> = {},
): OutgoingWebhook => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  format: faker.helpers.arrayElement(["native", "slack", "discord"] as const),
  events: faker.helpers.arrayElements([
    "message.created",
    "channel.created",
    "member.added",
  ] as const),
  isActive: faker.datatype.boolean(),
  secret: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  createdAt: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getListOutgoingWebhooksResponseMock = (
  overrideResponse: Partial<Extract<ListOutgoingWebhooks200, object>> = {},
): ListOutgoingWebhooks200 => ({
  webhooks: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    format: faker.helpers.arrayElement(["native", "slack", "discord"] as const),
    events: faker.helpers.arrayElements([
      "message.created",
      "channel.created",
      "member.added",
    ] as const),
    isActive: faker.datatype.boolean(),
    secret: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    createdAt: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  })),
  ...overrideResponse,
});
