/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  IncomingWebhook,
  ListIncomingWebhooks200,
  ListOutgoingWebhooks200,
  OutgoingWebhook,
} from "../../models";

export const getCreateIncomingWebhookResponseMock = (
  overrideResponse: Partial<Extract<IncomingWebhook, object>> = {},
): IncomingWebhook => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  channelId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getListIncomingWebhooksResponseMock = (
  overrideResponse: Partial<Extract<ListIncomingWebhooks200, object>> = {},
): ListIncomingWebhooks200 => ({
  webhooks: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    channelId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getCreateOutgoingWebhookResponseMock = (
  overrideResponse: Partial<Extract<OutgoingWebhook, object>> = {},
): OutgoingWebhook => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  format: faker.helpers.arrayElement(["native", "slack", "discord"] as const),
  events: faker.helpers.arrayElements([
    "message.created",
    "channel.created",
    "member.added",
  ] as const),
  isActive: faker.datatype.boolean(),
  secret: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  createdAt: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getListOutgoingWebhooksResponseMock = (
  overrideResponse: Partial<Extract<ListOutgoingWebhooks200, object>> = {},
): ListOutgoingWebhooks200 => ({
  webhooks: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    format: faker.helpers.arrayElement(["native", "slack", "discord"] as const),
    events: faker.helpers.arrayElements([
      "message.created",
      "channel.created",
      "member.added",
    ] as const),
    isActive: faker.datatype.boolean(),
    secret: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    createdAt: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getCreateIncomingWebhookMockHandler = (
  overrideResponse?:
    | IncomingWebhook
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<IncomingWebhook> | IncomingWebhook),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/workspaces/:workspaceId/channels/:channelId/incoming-webhooks",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateIncomingWebhookResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getListIncomingWebhooksMockHandler = (
  overrideResponse?:
    | ListIncomingWebhooks200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ListIncomingWebhooks200> | ListIncomingWebhooks200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/workspaces/:workspaceId/incoming-webhooks",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getListIncomingWebhooksResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeleteIncomingWebhookMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/workspaces/:workspaceId/incoming-webhooks/:webhookId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getCreateOutgoingWebhookMockHandler = (
  overrideResponse?:
    | OutgoingWebhook
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<OutgoingWebhook> | OutgoingWebhook),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/workspaces/:workspaceId/outgoing-webhooks",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateOutgoingWebhookResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getListOutgoingWebhooksMockHandler = (
  overrideResponse?:
    | ListOutgoingWebhooks200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ListOutgoingWebhooks200> | ListOutgoingWebhooks200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/workspaces/:workspaceId/outgoing-webhooks",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getListOutgoingWebhooksResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeleteOutgoingWebhookMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/workspaces/:workspaceId/outgoing-webhooks/:webhookId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getWebhookMock = () => [
  getCreateIncomingWebhookMockHandler(),
  getListIncomingWebhooksMockHandler(),
  getDeleteIncomingWebhookMockHandler(),
  getCreateOutgoingWebhookMockHandler(),
  getListOutgoingWebhooksMockHandler(),
  getDeleteOutgoingWebhookMockHandler(),
];
