/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Creates a token URL external services can POST to in order to post messages into the channel. Admins/owners only.
 * @summary Create an incoming webhook for a channel
 */
export const CreateIncomingWebhookParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
});

export const CreateIncomingWebhookBody = zod.object({
  name: zod.string(),
});

export const CreateIncomingWebhookResponse = zod.void();

/**
 * @summary List incoming webhooks
 */
export const ListIncomingWebhooksParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
});

export const ListIncomingWebhooksResponse = zod.object({
  webhooks: zod.array(
    zod.object({
      id: zod.string(),
      channelId: zod.string(),
      name: zod.string(),
      url: zod
        .string()
        .describe(
          "Relative URL external services POST to in order to post a message.",
        ),
      createdAt: zod.string().optional(),
    }),
  ),
});

/**
 * @summary Delete an incoming webhook
 */
export const DeleteIncomingWebhookParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  webhookId: zod.string(),
});

export const DeleteIncomingWebhookResponse = zod.unknown();

/**
 * Registers a URL that receives a POST on the selected workspace events. Format native (signed JSON), slack or discord. Admins/owners only.
 * @summary Create an outgoing webhook
 */
export const CreateOutgoingWebhookParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
});

export const CreateOutgoingWebhookBody = zod.object({
  name: zod.string(),
  url: zod.string(),
  format: zod.enum(["native", "slack", "discord"]),
  events: zod.array(
    zod.enum(["message.created", "channel.created", "member.added"]),
  ),
});

export const CreateOutgoingWebhookResponse = zod.void();

/**
 * @summary List outgoing webhooks
 */
export const ListOutgoingWebhooksParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
});

export const ListOutgoingWebhooksResponse = zod.object({
  webhooks: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      url: zod.string(),
      format: zod.enum(["native", "slack", "discord"]),
      events: zod.array(
        zod.enum(["message.created", "channel.created", "member.added"]),
      ),
      isActive: zod.boolean(),
      secret: zod
        .string()
        .optional()
        .describe(
          "HMAC signing secret (returned only when the webhook is created).",
        ),
      createdAt: zod.string().optional(),
    }),
  ),
});

/**
 * @summary Delete an outgoing webhook
 */
export const DeleteOutgoingWebhookParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  webhookId: zod.string(),
});

export const DeleteOutgoingWebhookResponse = zod.unknown();
