/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CreateIncomingWebhookBody,
  CreateOutgoingWebhookBody,
  IncomingWebhook,
  ListIncomingWebhooks200,
  ListOutgoingWebhooks200,
  N401Response,
  N403Response,
  N404Response,
  OutgoingWebhook,
} from "../../models";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Creates a token URL external services can POST to in order to post messages into the channel. Admins/owners only.
 * @summary Create an incoming webhook for a channel
 */
export const createIncomingWebhook = (
  workspaceId: string,
  channelId: string,
  createIncomingWebhookBody: CreateIncomingWebhookBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IncomingWebhook>> => {
  return axios.post(
    `/workspaces/${workspaceId}/channels/${channelId}/incoming-webhooks`,
    createIncomingWebhookBody,
    options,
  );
};

export const getCreateIncomingWebhookMutationOptions = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createIncomingWebhook>>,
    TError,
    { workspaceId: string; channelId: string; data: CreateIncomingWebhookBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createIncomingWebhook>>,
  TError,
  { workspaceId: string; channelId: string; data: CreateIncomingWebhookBody },
  TContext
> => {
  const mutationKey = ["createIncomingWebhook"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createIncomingWebhook>>,
    { workspaceId: string; channelId: string; data: CreateIncomingWebhookBody }
  > = (props) => {
    const { workspaceId, channelId, data } = props ?? {};

    return createIncomingWebhook(workspaceId, channelId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateIncomingWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof createIncomingWebhook>>
>;
export type CreateIncomingWebhookMutationBody = CreateIncomingWebhookBody;
export type CreateIncomingWebhookMutationError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary Create an incoming webhook for a channel
 */
export const useCreateIncomingWebhook = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createIncomingWebhook>>,
    TError,
    { workspaceId: string; channelId: string; data: CreateIncomingWebhookBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof createIncomingWebhook>>,
  TError,
  { workspaceId: string; channelId: string; data: CreateIncomingWebhookBody },
  TContext
> => {
  return useMutation(getCreateIncomingWebhookMutationOptions(options));
};
/**
 * @summary List incoming webhooks
 */
export const listIncomingWebhooks = (
  workspaceId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ListIncomingWebhooks200>> => {
  return axios.get(`/workspaces/${workspaceId}/incoming-webhooks`, options);
};

export const getListIncomingWebhooksQueryKey = (workspaceId: string) => {
  return [`/workspaces/${workspaceId}/incoming-webhooks`] as const;
};

export const getListIncomingWebhooksQueryOptions = <
  TData = Awaited<ReturnType<typeof listIncomingWebhooks>>,
  TError = AxiosError<N401Response | N403Response | N404Response>,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listIncomingWebhooks>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListIncomingWebhooksQueryKey(workspaceId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listIncomingWebhooks>>
  > = ({ signal }) =>
    listIncomingWebhooks(workspaceId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: workspaceId !== null && workspaceId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listIncomingWebhooks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListIncomingWebhooksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listIncomingWebhooks>>
>;
export type ListIncomingWebhooksQueryError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary List incoming webhooks
 */

export function useListIncomingWebhooks<
  TData = Awaited<ReturnType<typeof listIncomingWebhooks>>,
  TError = AxiosError<N401Response | N403Response | N404Response>,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listIncomingWebhooks>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListIncomingWebhooksQueryOptions(
    workspaceId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete an incoming webhook
 */
export const deleteIncomingWebhook = (
  workspaceId: string,
  webhookId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(
    `/workspaces/${workspaceId}/incoming-webhooks/${webhookId}`,
    options,
  );
};

export const getDeleteIncomingWebhookMutationOptions = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteIncomingWebhook>>,
    TError,
    { workspaceId: string; webhookId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteIncomingWebhook>>,
  TError,
  { workspaceId: string; webhookId: string },
  TContext
> => {
  const mutationKey = ["deleteIncomingWebhook"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteIncomingWebhook>>,
    { workspaceId: string; webhookId: string }
  > = (props) => {
    const { workspaceId, webhookId } = props ?? {};

    return deleteIncomingWebhook(workspaceId, webhookId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteIncomingWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteIncomingWebhook>>
>;

export type DeleteIncomingWebhookMutationError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary Delete an incoming webhook
 */
export const useDeleteIncomingWebhook = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteIncomingWebhook>>,
    TError,
    { workspaceId: string; webhookId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteIncomingWebhook>>,
  TError,
  { workspaceId: string; webhookId: string },
  TContext
> => {
  return useMutation(getDeleteIncomingWebhookMutationOptions(options));
};
/**
 * Registers a URL that receives a POST on the selected workspace events. Format native (signed JSON), slack or discord. Admins/owners only.
 * @summary Create an outgoing webhook
 */
export const createOutgoingWebhook = (
  workspaceId: string,
  createOutgoingWebhookBody: CreateOutgoingWebhookBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<OutgoingWebhook>> => {
  return axios.post(
    `/workspaces/${workspaceId}/outgoing-webhooks`,
    createOutgoingWebhookBody,
    options,
  );
};

export const getCreateOutgoingWebhookMutationOptions = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOutgoingWebhook>>,
    TError,
    { workspaceId: string; data: CreateOutgoingWebhookBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOutgoingWebhook>>,
  TError,
  { workspaceId: string; data: CreateOutgoingWebhookBody },
  TContext
> => {
  const mutationKey = ["createOutgoingWebhook"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOutgoingWebhook>>,
    { workspaceId: string; data: CreateOutgoingWebhookBody }
  > = (props) => {
    const { workspaceId, data } = props ?? {};

    return createOutgoingWebhook(workspaceId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOutgoingWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOutgoingWebhook>>
>;
export type CreateOutgoingWebhookMutationBody = CreateOutgoingWebhookBody;
export type CreateOutgoingWebhookMutationError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary Create an outgoing webhook
 */
export const useCreateOutgoingWebhook = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOutgoingWebhook>>,
    TError,
    { workspaceId: string; data: CreateOutgoingWebhookBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOutgoingWebhook>>,
  TError,
  { workspaceId: string; data: CreateOutgoingWebhookBody },
  TContext
> => {
  return useMutation(getCreateOutgoingWebhookMutationOptions(options));
};
/**
 * @summary List outgoing webhooks
 */
export const listOutgoingWebhooks = (
  workspaceId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ListOutgoingWebhooks200>> => {
  return axios.get(`/workspaces/${workspaceId}/outgoing-webhooks`, options);
};

export const getListOutgoingWebhooksQueryKey = (workspaceId: string) => {
  return [`/workspaces/${workspaceId}/outgoing-webhooks`] as const;
};

export const getListOutgoingWebhooksQueryOptions = <
  TData = Awaited<ReturnType<typeof listOutgoingWebhooks>>,
  TError = AxiosError<N401Response | N403Response | N404Response>,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOutgoingWebhooks>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListOutgoingWebhooksQueryKey(workspaceId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOutgoingWebhooks>>
  > = ({ signal }) =>
    listOutgoingWebhooks(workspaceId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: workspaceId !== null && workspaceId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listOutgoingWebhooks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOutgoingWebhooksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOutgoingWebhooks>>
>;
export type ListOutgoingWebhooksQueryError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary List outgoing webhooks
 */

export function useListOutgoingWebhooks<
  TData = Awaited<ReturnType<typeof listOutgoingWebhooks>>,
  TError = AxiosError<N401Response | N403Response | N404Response>,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOutgoingWebhooks>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOutgoingWebhooksQueryOptions(
    workspaceId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete an outgoing webhook
 */
export const deleteOutgoingWebhook = (
  workspaceId: string,
  webhookId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(
    `/workspaces/${workspaceId}/outgoing-webhooks/${webhookId}`,
    options,
  );
};

export const getDeleteOutgoingWebhookMutationOptions = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOutgoingWebhook>>,
    TError,
    { workspaceId: string; webhookId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOutgoingWebhook>>,
  TError,
  { workspaceId: string; webhookId: string },
  TContext
> => {
  const mutationKey = ["deleteOutgoingWebhook"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOutgoingWebhook>>,
    { workspaceId: string; webhookId: string }
  > = (props) => {
    const { workspaceId, webhookId } = props ?? {};

    return deleteOutgoingWebhook(workspaceId, webhookId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOutgoingWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOutgoingWebhook>>
>;

export type DeleteOutgoingWebhookMutationError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary Delete an outgoing webhook
 */
export const useDeleteOutgoingWebhook = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOutgoingWebhook>>,
    TError,
    { workspaceId: string; webhookId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteOutgoingWebhook>>,
  TError,
  { workspaceId: string; webhookId: string },
  TContext
> => {
  return useMutation(getDeleteOutgoingWebhookMutationOptions(options));
};
