/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  LoginResponseResponse,
  LogoutResponseResponse,
  TokenRefreshResponseResponse,
} from "../../models";

export const getRegisterUserMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/auth/register",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getLoginUserMockHandler = (
  overrideResponse?:
    | LoginResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<LoginResponseResponse> | LoginResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/auth/login",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGoogleAuthMockHandler = (
  overrideResponse?:
    | LoginResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<LoginResponseResponse> | LoginResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/auth/google",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getRefreshTokenMockHandler = (
  overrideResponse?:
    | TokenRefreshResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<TokenRefreshResponseResponse>
        | TokenRefreshResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/auth/refresh",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getLogoutUserMockHandler = (
  overrideResponse?:
    | LogoutResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<LogoutResponseResponse> | LogoutResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/auth/logout",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getAuthMock = () => [
  getRegisterUserMockHandler(),
  getLoginUserMockHandler(),
  getGoogleAuthMockHandler(),
  getRefreshTokenMockHandler(),
  getLogoutUserMockHandler(),
];
