/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  GoogleAuthRequestBody,
  LoginRequestBody,
  LoginResponseResponse,
  LogoutResponseResponse,
  N400Response,
  N401Response,
  N403Response,
  N409Response,
  RegisterRequestBody,
  TokenRefreshResponseResponse,
} from "../../models";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Create a new user account with the provided information. The profile picture is optional and can be uploaded as part of the registration process.
 * @summary Register a new user
 */
export const registerUser = (
  registerRequestBody: RegisterRequestBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  const formData = new FormData();
  formData.append(`name`, registerRequestBody.name);
  formData.append(`surname`, registerRequestBody.surname);
  formData.append(`email`, registerRequestBody.email);
  formData.append(`password`, registerRequestBody.password);
  if (registerRequestBody.avatar !== undefined) {
    formData.append(`avatar`, registerRequestBody.avatar);
  }

  return axios.post(
    `http://localhost:5000/api/auth/register`,
    formData,
    options,
  );
};

export const getRegisterUserMutationOptions = <
  TError = AxiosError<N400Response | N409Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: RegisterRequestBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: RegisterRequestBody },
  TContext
> => {
  const mutationKey = ["registerUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    { data: RegisterRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUser>>
>;
export type RegisterUserMutationBody = RegisterRequestBody;
export type RegisterUserMutationError = AxiosError<N400Response | N409Response>;

/**
 * @summary Register a new user
 */
export const useRegisterUser = <
  TError = AxiosError<N400Response | N409Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: RegisterRequestBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: RegisterRequestBody },
  TContext
> => {
  return useMutation(getRegisterUserMutationOptions(options));
};
/**
 * Authenticate a user with their email and password. On successful authentication, sets both access_token and refresh_token cookies for session management.
 * @summary Log in a user and obtain an authentication token
 */
export const loginUser = (
  loginRequestBody: LoginRequestBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LoginResponseResponse>> => {
  return axios.post(
    `http://localhost:5000/api/auth/login`,
    loginRequestBody,
    options,
  );
};

export const getLoginUserMutationOptions = <
  TError = AxiosError<N400Response | N401Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: LoginRequestBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: LoginRequestBody },
  TContext
> => {
  const mutationKey = ["loginUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    { data: LoginRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = LoginRequestBody;
export type LoginUserMutationError = AxiosError<N400Response | N401Response>;

/**
 * @summary Log in a user and obtain an authentication token
 */
export const useLoginUser = <
  TError = AxiosError<N400Response | N401Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: LoginRequestBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: LoginRequestBody },
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options));
};
/**
 * Authenticate a user with a Google OAuth token. On successful authentication, sets both access_token and refresh_token cookies for session management.
 * @summary Authenticate a user using Google OAuth token
 */
export const googleAuth = (
  googleAuthRequestBody: GoogleAuthRequestBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LoginResponseResponse>> => {
  return axios.post(
    `http://localhost:5000/api/auth/google`,
    googleAuthRequestBody,
    options,
  );
};

export const getGoogleAuthMutationOptions = <
  TError = AxiosError<N400Response | N401Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof googleAuth>>,
    TError,
    { data: GoogleAuthRequestBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof googleAuth>>,
  TError,
  { data: GoogleAuthRequestBody },
  TContext
> => {
  const mutationKey = ["googleAuth"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof googleAuth>>,
    { data: GoogleAuthRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return googleAuth(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoogleAuthMutationResult = NonNullable<
  Awaited<ReturnType<typeof googleAuth>>
>;
export type GoogleAuthMutationBody = GoogleAuthRequestBody;
export type GoogleAuthMutationError = AxiosError<N400Response | N401Response>;

/**
 * @summary Authenticate a user using Google OAuth token
 */
export const useGoogleAuth = <
  TError = AxiosError<N400Response | N401Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof googleAuth>>,
    TError,
    { data: GoogleAuthRequestBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof googleAuth>>,
  TError,
  { data: GoogleAuthRequestBody },
  TContext
> => {
  return useMutation(getGoogleAuthMutationOptions(options));
};
/**
 * Use the refresh token to obtain a new access token. This endpoint requires a valid refresh_token cookie and will set a new access_token cookie on success.
 * @summary Refresh the authentication token using the refresh token
 */
export const refreshToken = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TokenRefreshResponseResponse>> => {
  return axios.post(
    `http://localhost:5000/api/auth/refresh`,
    undefined,
    options,
  );
};

export const getRefreshTokenMutationOptions = <
  TError = AxiosError<N401Response | N403Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["refreshToken"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    void
  > = () => {
    return refreshToken(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;

export type RefreshTokenMutationError = AxiosError<N401Response | N403Response>;

/**
 * @summary Refresh the authentication token using the refresh token
 */
export const useRefreshToken = <
  TError = AxiosError<N401Response | N403Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getRefreshTokenMutationOptions(options));
};
/**
 * Log out the currently authenticated user by clearing the access_token and refresh_token cookies.
 * @summary Log out the authenticated user
 */
export const logoutUser = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LogoutResponseResponse>> => {
  return axios.post(
    `http://localhost:5000/api/auth/logout`,
    undefined,
    options,
  );
};

export const getLogoutUserMutationOptions = <
  TError = AxiosError<N401Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutUser>>,
    void
  > = () => {
    return logoutUser(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutUser>>
>;

export type LogoutUserMutationError = AxiosError<N401Response>;

/**
 * @summary Log out the authenticated user
 */
export const useLogoutUser = <
  TError = AxiosError<N401Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutUserMutationOptions(options));
};
