/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Create a new user account with the provided information. The profile picture is optional and can be uploaded as part of the registration process.
 * @summary Register a new user
 */
export const RegisterUserBody = zod.object({
  name: zod.string(),
  surname: zod.string(),
  email: zod.string().email(),
  password: zod.string(),
  avatar: zod
    .instanceof(File)
    .optional()
    .describe("Optional avatar image file"),
});

export const RegisterUserResponse = zod.void();

/**
 * Authenticate a user with their email and password. On successful authentication, sets both access_token and refresh_token cookies for session management.
 * @summary Log in a user and obtain an authentication token
 */
export const LoginUserBody = zod.object({
  email: zod.string().email(),
  password: zod.string(),
});

export const LoginUserResponse = zod.unknown();

/**
 * Authenticate a user with a Google OAuth token. On successful authentication, sets both access_token and refresh_token cookies for session management.
 * @summary Authenticate a user using Google OAuth token
 */
export const GoogleAuthBody = zod.object({
  token: zod.string().describe("Google OAuth token obtained from the client"),
});

export const GoogleAuthResponse = zod.unknown();

/**
 * Use the refresh token to obtain a new access token. This endpoint requires a valid refresh_token cookie and will set a new access_token cookie on success.
 * @summary Refresh the authentication token using the refresh token
 */
export const RefreshTokenResponse = zod.unknown();

/**
 * Log out the currently authenticated user by clearing the access_token and refresh_token cookies.
 * @summary Log out the authenticated user
 */
export const LogoutUserResponse = zod.unknown();
