/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';


/**
 * @summary Create a new workspace
 */
export const CreateWorkspaceBody = zod.object({
  "workspaceName": zod.string()
})

export const CreateWorkspaceResponse = zod.object({
  "clientSecret": zod.string().describe('Secret key generated by Stripe for processing the payment')
})

/**
 * @summary Confirm the workspace payment after successful Stripe transaction
 */
export const ConfirmWorkspacePaymentBody = zod.object({
  "paymentIntentId": zod.string().describe('ID of the Stripe Payment Intent to confirm'),
  "workspaceName": zod.string()
})

export const ConfirmWorkspacePaymentResponse = zod.void()

