/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  faker
} from '@faker-js/faker';

import type {
  CreatePaymentResponse,
  Workspace
} from '../../models';


export const getGetUserWorkspacesResponseMock = (): Workspace[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), logoUrl: faker.helpers.arrayElement([faker.internet.url(), undefined])})))

export const getCreateWorkspaceResponseMock = (overrideResponse: Partial<Extract<CreatePaymentResponse, object>> = {}): CreatePaymentResponse => ({clientSecret: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

