/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConfirmWorkspacePaymentRequest,
  CreatePaymentResponse,
  CreateWorkspaceRequest,
  ErrorResponse,
  Workspace
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type getUserWorkspacesResponse200 = {
  data: Workspace[]
  status: 200
}

export type getUserWorkspacesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getUserWorkspacesResponseSuccess = (getUserWorkspacesResponse200) & {
  headers: Headers;
};
export type getUserWorkspacesResponseError = (getUserWorkspacesResponse401) & {
  headers: Headers;
};

export type getUserWorkspacesResponse = (getUserWorkspacesResponseSuccess | getUserWorkspacesResponseError)

export const getGetUserWorkspacesUrl = () => {




  return `/workspace`
}

/**
 * @summary Get a list of workspaces the authenticated user belongs to
 */
export const getUserWorkspaces = async ( options?: RequestInit): Promise<getUserWorkspacesResponse> => {

  const res = await fetch(getGetUserWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserWorkspacesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserWorkspacesResponse
}





export const getGetUserWorkspacesInfiniteQueryKey = () => {
    return [
    'infinite', `/workspace`
    ] as const;
    }

export const getGetUserWorkspacesQueryKey = () => {
    return [
    `/workspace`
    ] as const;
    }


export const getGetUserWorkspacesInfiniteQueryOptions = <TData = Awaited<ReturnType<typeof getUserWorkspaces>>, TError = ErrorResponse>( options?: { query?:UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserWorkspaces>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserWorkspacesInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserWorkspaces>>> = ({ signal }) => getUserWorkspaces({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserWorkspaces>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserWorkspacesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUserWorkspaces>>>
export type GetUserWorkspacesInfiniteQueryError = ErrorResponse


/**
 * @summary Get a list of workspaces the authenticated user belongs to
 */

export function useGetUserWorkspacesInfinite<TData = Awaited<ReturnType<typeof getUserWorkspaces>>, TError = ErrorResponse>(
  options?: { query?:UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserWorkspaces>>, TError, TData>, fetch?: RequestInit}

 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserWorkspacesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetUserWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof getUserWorkspaces>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserWorkspaces>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserWorkspacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserWorkspaces>>> = ({ signal }) => getUserWorkspaces({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserWorkspaces>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof getUserWorkspaces>>>
export type GetUserWorkspacesQueryError = ErrorResponse


/**
 * @summary Get a list of workspaces the authenticated user belongs to
 */

export function useGetUserWorkspaces<TData = Awaited<ReturnType<typeof getUserWorkspaces>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserWorkspaces>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserWorkspacesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createWorkspaceResponse200 = {
  data: CreatePaymentResponse
  status: 200
}

export type createWorkspaceResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createWorkspaceResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createWorkspaceResponse409 = {
  data: ErrorResponse
  status: 409
}

export type createWorkspaceResponseSuccess = (createWorkspaceResponse200) & {
  headers: Headers;
};
export type createWorkspaceResponseError = (createWorkspaceResponse400 | createWorkspaceResponse401 | createWorkspaceResponse409) & {
  headers: Headers;
};

export type createWorkspaceResponse = (createWorkspaceResponseSuccess | createWorkspaceResponseError)

export const getCreateWorkspaceUrl = () => {




  return `/workspace/create`
}

/**
 * @summary Create a new workspace
 */
export const createWorkspace = async (createWorkspaceRequest: CreateWorkspaceRequest, options?: RequestInit): Promise<createWorkspaceResponse> => {

  const res = await fetch(getCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkspaceRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createWorkspaceResponse
}





export const getCreateWorkspaceQueryKey = (createWorkspaceRequest?: CreateWorkspaceRequest,) => {
    return [
    'POST', `/workspace/create`, createWorkspaceRequest
    ] as const;
    }


export const getCreateWorkspaceQueryOptions = <TData = Awaited<ReturnType<typeof createWorkspace>>, TError = ErrorResponse>(createWorkspaceRequest: CreateWorkspaceRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof createWorkspace>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateWorkspaceQueryKey(createWorkspaceRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createWorkspace>>> = ({ signal }) => createWorkspace(createWorkspaceRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createWorkspace>>, TError, TData> & { queryKey: QueryKey }
}

export type CreateWorkspaceQueryResult = NonNullable<Awaited<ReturnType<typeof createWorkspace>>>
export type CreateWorkspaceQueryError = ErrorResponse


/**
 * @summary Create a new workspace
 */

export function useCreateWorkspace<TData = Awaited<ReturnType<typeof createWorkspace>>, TError = ErrorResponse>(
 createWorkspaceRequest: CreateWorkspaceRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof createWorkspace>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCreateWorkspaceQueryOptions(createWorkspaceRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type confirmWorkspacePaymentResponse202 = {
  data: void
  status: 202
}

export type confirmWorkspacePaymentResponse400 = {
  data: ErrorResponse
  status: 400
}

export type confirmWorkspacePaymentResponse401 = {
  data: ErrorResponse
  status: 401
}

export type confirmWorkspacePaymentResponse402 = {
  data: ErrorResponse
  status: 402
}

export type confirmWorkspacePaymentResponse409 = {
  data: ErrorResponse
  status: 409
}

export type confirmWorkspacePaymentResponseSuccess = (confirmWorkspacePaymentResponse202) & {
  headers: Headers;
};
export type confirmWorkspacePaymentResponseError = (confirmWorkspacePaymentResponse400 | confirmWorkspacePaymentResponse401 | confirmWorkspacePaymentResponse402 | confirmWorkspacePaymentResponse409) & {
  headers: Headers;
};

export type confirmWorkspacePaymentResponse = (confirmWorkspacePaymentResponseSuccess | confirmWorkspacePaymentResponseError)

export const getConfirmWorkspacePaymentUrl = () => {




  return `/workspace/confirm-payment`
}

/**
 * @summary Confirm the workspace payment after successful Stripe transaction
 */
export const confirmWorkspacePayment = async (confirmWorkspacePaymentRequest: ConfirmWorkspacePaymentRequest, options?: RequestInit): Promise<confirmWorkspacePaymentResponse> => {
    const formData = new FormData();
formData.append(`paymentIntentId`, confirmWorkspacePaymentRequest.paymentIntentId);
formData.append(`workspaceName`, confirmWorkspacePaymentRequest.workspaceName);
if(confirmWorkspacePaymentRequest.workspaceLogo !== undefined) {
 formData.append(`workspaceLogo`, confirmWorkspacePaymentRequest.workspaceLogo);
 }

  const res = await fetch(getConfirmWorkspacePaymentUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: confirmWorkspacePaymentResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as confirmWorkspacePaymentResponse
}





export const getConfirmWorkspacePaymentQueryKey = (confirmWorkspacePaymentRequest?: ConfirmWorkspacePaymentRequest,) => {
    return [
    'POST', `/workspace/confirm-payment`, confirmWorkspacePaymentRequest
    ] as const;
    }


export const getConfirmWorkspacePaymentQueryOptions = <TData = Awaited<ReturnType<typeof confirmWorkspacePayment>>, TError = ErrorResponse>(confirmWorkspacePaymentRequest: ConfirmWorkspacePaymentRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof confirmWorkspacePayment>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConfirmWorkspacePaymentQueryKey(confirmWorkspacePaymentRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof confirmWorkspacePayment>>> = ({ signal }) => confirmWorkspacePayment(confirmWorkspacePaymentRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof confirmWorkspacePayment>>, TError, TData> & { queryKey: QueryKey }
}

export type ConfirmWorkspacePaymentQueryResult = NonNullable<Awaited<ReturnType<typeof confirmWorkspacePayment>>>
export type ConfirmWorkspacePaymentQueryError = ErrorResponse


/**
 * @summary Confirm the workspace payment after successful Stripe transaction
 */

export function useConfirmWorkspacePayment<TData = Awaited<ReturnType<typeof confirmWorkspacePayment>>, TError = ErrorResponse>(
 confirmWorkspacePaymentRequest: ConfirmWorkspacePaymentRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof confirmWorkspacePayment>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getConfirmWorkspacePaymentQueryOptions(confirmWorkspacePaymentRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






