/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChannelListResponseResponse,
  CreateChannelRequestBody,
  N400Response,
  N401Response,
  N403Response,
  N404Response,
  UpdateChannelNameRequestBody
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type createChannelResponse201 = {
  data: void
  status: 201
}

export type createChannelResponse400 = {
  data: N400Response
  status: 400
}

export type createChannelResponse401 = {
  data: N401Response
  status: 401
}

export type createChannelResponse403 = {
  data: N403Response
  status: 403
}

export type createChannelResponse404 = {
  data: N404Response
  status: 404
}

export type createChannelResponseSuccess = (createChannelResponse201) & {
  headers: Headers;
};
export type createChannelResponseError = (createChannelResponse400 | createChannelResponse401 | createChannelResponse403 | createChannelResponse404) & {
  headers: Headers;
};

export type createChannelResponse = (createChannelResponseSuccess | createChannelResponseError)

export const getCreateChannelUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}/channels`
}

/**
 * Create a new channel within the specified workspace. The user creating the channel will be added as a member of that channel. Only owners and admins of the workspace can create channels.
 * @summary Create a new channel in a workspace
 */
export const createChannel = async (workspaceId: string,
    createChannelRequestBody: CreateChannelRequestBody, options?: RequestInit): Promise<createChannelResponse> => {

  const res = await fetch(getCreateChannelUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createChannelRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createChannelResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as createChannelResponse
}




export const getCreateChannelMutationOptions = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChannel>>, TError,{workspaceId: string;data: CreateChannelRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createChannel>>, TError,{workspaceId: string;data: CreateChannelRequestBody}, TContext> => {

const mutationKey = ['createChannel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createChannel>>, {workspaceId: string;data: CreateChannelRequestBody}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  createChannel(workspaceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateChannelMutationResult = NonNullable<Awaited<ReturnType<typeof createChannel>>>
    export type CreateChannelMutationBody = CreateChannelRequestBody
    export type CreateChannelMutationError = N400Response | N401Response | N403Response | N404Response

    /**
 * @summary Create a new channel in a workspace
 */
export const useCreateChannel = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChannel>>, TError,{workspaceId: string;data: CreateChannelRequestBody}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createChannel>>,
        TError,
        {workspaceId: string;data: CreateChannelRequestBody},
        TContext
      > => {
      return useMutation(getCreateChannelMutationOptions(options));
    }
    export type listChannelsResponse200 = {
  data: ChannelListResponseResponse
  status: 200
}

export type listChannelsResponse400 = {
  data: N400Response
  status: 400
}

export type listChannelsResponse401 = {
  data: N401Response
  status: 401
}

export type listChannelsResponse403 = {
  data: N403Response
  status: 403
}

export type listChannelsResponse404 = {
  data: N404Response
  status: 404
}

export type listChannelsResponseSuccess = (listChannelsResponse200) & {
  headers: Headers;
};
export type listChannelsResponseError = (listChannelsResponse400 | listChannelsResponse401 | listChannelsResponse403 | listChannelsResponse404) & {
  headers: Headers;
};

export type listChannelsResponse = (listChannelsResponseSuccess | listChannelsResponseError)

export const getListChannelsUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}/channels`
}

/**
 * Retrieve a list of all channels within the specified workspace.
 * @summary List all channels in a workspace
 */
export const listChannels = async (workspaceId: string, options?: RequestInit): Promise<listChannelsResponse> => {

  const res = await fetch(getListChannelsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listChannelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listChannelsResponse
}





export const getListChannelsQueryKey = (workspaceId: string,) => {
    return [
    `/workspaces/${workspaceId}/channels`
    ] as const;
    }


export const getListChannelsQueryOptions = <TData = Awaited<ReturnType<typeof listChannels>>, TError = N400Response | N401Response | N403Response | N404Response>(workspaceId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChannelsQueryKey(workspaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChannels>>> = ({ signal }) => listChannels(workspaceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: workspaceId !== null && workspaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData> & { queryKey: QueryKey }
}

export type ListChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof listChannels>>>
export type ListChannelsQueryError = N400Response | N401Response | N403Response | N404Response


/**
 * @summary List all channels in a workspace
 */

export function useListChannels<TData = Awaited<ReturnType<typeof listChannels>>, TError = N400Response | N401Response | N403Response | N404Response>(
 workspaceId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListChannelsQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateChannelNameResponse200 = {
  data: void
  status: 200
}

export type updateChannelNameResponse400 = {
  data: N400Response
  status: 400
}

export type updateChannelNameResponse401 = {
  data: N401Response
  status: 401
}

export type updateChannelNameResponse403 = {
  data: N403Response
  status: 403
}

export type updateChannelNameResponse404 = {
  data: N404Response
  status: 404
}

export type updateChannelNameResponseSuccess = (updateChannelNameResponse200) & {
  headers: Headers;
};
export type updateChannelNameResponseError = (updateChannelNameResponse400 | updateChannelNameResponse401 | updateChannelNameResponse403 | updateChannelNameResponse404) & {
  headers: Headers;
};

export type updateChannelNameResponse = (updateChannelNameResponseSuccess | updateChannelNameResponseError)

export const getUpdateChannelNameUrl = (workspaceId: string,
    channelId: string,) => {




  return `/workspaces/${workspaceId}/channels/${channelId}`
}

/**
 * Update the name of an existing channel within the specified workspace. Only owners and admins of the workspace can update channel names.
 * @summary Update the name of a channel
 */
export const updateChannelName = async (workspaceId: string,
    channelId: string,
    updateChannelNameRequestBody: UpdateChannelNameRequestBody, options?: RequestInit): Promise<updateChannelNameResponse> => {

  const res = await fetch(getUpdateChannelNameUrl(workspaceId,channelId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateChannelNameRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateChannelNameResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as updateChannelNameResponse
}




export const getUpdateChannelNameMutationOptions = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChannelName>>, TError,{workspaceId: string;channelId: string;data: UpdateChannelNameRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateChannelName>>, TError,{workspaceId: string;channelId: string;data: UpdateChannelNameRequestBody}, TContext> => {

const mutationKey = ['updateChannelName'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateChannelName>>, {workspaceId: string;channelId: string;data: UpdateChannelNameRequestBody}> = (props) => {
          const {workspaceId,channelId,data} = props ?? {};

          return  updateChannelName(workspaceId,channelId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateChannelNameMutationResult = NonNullable<Awaited<ReturnType<typeof updateChannelName>>>
    export type UpdateChannelNameMutationBody = UpdateChannelNameRequestBody
    export type UpdateChannelNameMutationError = N400Response | N401Response | N403Response | N404Response

    /**
 * @summary Update the name of a channel
 */
export const useUpdateChannelName = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChannelName>>, TError,{workspaceId: string;channelId: string;data: UpdateChannelNameRequestBody}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateChannelName>>,
        TError,
        {workspaceId: string;channelId: string;data: UpdateChannelNameRequestBody},
        TContext
      > => {
      return useMutation(getUpdateChannelNameMutationOptions(options));
    }
    export type deleteChannelResponse200 = {
  data: void
  status: 200
}

export type deleteChannelResponse400 = {
  data: N400Response
  status: 400
}

export type deleteChannelResponse401 = {
  data: N401Response
  status: 401
}

export type deleteChannelResponse403 = {
  data: N403Response
  status: 403
}

export type deleteChannelResponse404 = {
  data: N404Response
  status: 404
}

export type deleteChannelResponseSuccess = (deleteChannelResponse200) & {
  headers: Headers;
};
export type deleteChannelResponseError = (deleteChannelResponse400 | deleteChannelResponse401 | deleteChannelResponse403 | deleteChannelResponse404) & {
  headers: Headers;
};

export type deleteChannelResponse = (deleteChannelResponseSuccess | deleteChannelResponseError)

export const getDeleteChannelUrl = (workspaceId: string,
    channelId: string,) => {




  return `/workspaces/${workspaceId}/channels/${channelId}`
}

/**
 * Delete an existing channel from the specified workspace. Only owners and admins of the workspace can delete channels.
 * @summary Delete a channel from a workspace
 */
export const deleteChannel = async (workspaceId: string,
    channelId: string, options?: RequestInit): Promise<deleteChannelResponse> => {

  const res = await fetch(getDeleteChannelUrl(workspaceId,channelId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteChannelResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteChannelResponse
}




export const getDeleteChannelMutationOptions = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChannel>>, TError,{workspaceId: string;channelId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChannel>>, TError,{workspaceId: string;channelId: string}, TContext> => {

const mutationKey = ['deleteChannel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChannel>>, {workspaceId: string;channelId: string}> = (props) => {
          const {workspaceId,channelId} = props ?? {};

          return  deleteChannel(workspaceId,channelId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteChannelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChannel>>>

    export type DeleteChannelMutationError = N400Response | N401Response | N403Response | N404Response

    /**
 * @summary Delete a channel from a workspace
 */
export const useDeleteChannel = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChannel>>, TError,{workspaceId: string;channelId: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteChannel>>,
        TError,
        {workspaceId: string;channelId: string},
        TContext
      > => {
      return useMutation(getDeleteChannelMutationOptions(options));
    }
