/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ChannelListResponse,
  CreateChannelBody,
  N400Response,
  N401Response,
  N403Response,
  N404Response,
  UpdateChannelNameBody,
} from "../../models";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Create a new channel within the specified workspace. The user creating the channel will be added as a member of that channel. Only owners and admins of the workspace can create channels.
 * @summary Create a new channel in a workspace
 */
export const createChannel = (
  workspaceId: string,
  createChannelBody: CreateChannelBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/workspaces/${workspaceId}/channels`,
    createChannelBody,
    options,
  );
};

export const getCreateChannelMutationOptions = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChannel>>,
    TError,
    { workspaceId: string; data: CreateChannelBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChannel>>,
  TError,
  { workspaceId: string; data: CreateChannelBody },
  TContext
> => {
  const mutationKey = ["createChannel"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChannel>>,
    { workspaceId: string; data: CreateChannelBody }
  > = (props) => {
    const { workspaceId, data } = props ?? {};

    return createChannel(workspaceId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChannelMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChannel>>
>;
export type CreateChannelMutationBody = CreateChannelBody;
export type CreateChannelMutationError = AxiosError<
  N400Response | N401Response | N403Response | N404Response
>;

/**
 * @summary Create a new channel in a workspace
 */
export const useCreateChannel = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChannel>>,
    TError,
    { workspaceId: string; data: CreateChannelBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof createChannel>>,
  TError,
  { workspaceId: string; data: CreateChannelBody },
  TContext
> => {
  return useMutation(getCreateChannelMutationOptions(options));
};
/**
 * Retrieve a list of all channels within the specified workspace.
 * @summary List all channels in a workspace
 */
export const listChannels = (
  workspaceId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ChannelListResponse>> => {
  return axios.get(`/workspaces/${workspaceId}/channels`, options);
};

export const getListChannelsQueryKey = (workspaceId: string) => {
  return [`/workspaces/${workspaceId}/channels`] as const;
};

export const getListChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof listChannels>>,
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listChannels>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListChannelsQueryKey(workspaceId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listChannels>>> = ({
    signal,
  }) => listChannels(workspaceId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: workspaceId !== null && workspaceId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listChannels>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listChannels>>
>;
export type ListChannelsQueryError = AxiosError<
  N400Response | N401Response | N403Response | N404Response
>;

/**
 * @summary List all channels in a workspace
 */

export function useListChannels<
  TData = Awaited<ReturnType<typeof listChannels>>,
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listChannels>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListChannelsQueryOptions(workspaceId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Marks the channel as read for the authenticated user, clearing its unread message count.
 * @summary Mark a channel as read
 */
export const markChannelRead = (
  workspaceId: string,
  channelId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/workspaces/${workspaceId}/channels/${channelId}/read`,
    undefined,
    options,
  );
};

export const getMarkChannelReadMutationOptions = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markChannelRead>>,
    TError,
    { workspaceId: string; channelId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markChannelRead>>,
  TError,
  { workspaceId: string; channelId: string },
  TContext
> => {
  const mutationKey = ["markChannelRead"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markChannelRead>>,
    { workspaceId: string; channelId: string }
  > = (props) => {
    const { workspaceId, channelId } = props ?? {};

    return markChannelRead(workspaceId, channelId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkChannelReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof markChannelRead>>
>;

export type MarkChannelReadMutationError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary Mark a channel as read
 */
export const useMarkChannelRead = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markChannelRead>>,
    TError,
    { workspaceId: string; channelId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof markChannelRead>>,
  TError,
  { workspaceId: string; channelId: string },
  TContext
> => {
  return useMutation(getMarkChannelReadMutationOptions(options));
};
/**
 * Update the name of an existing channel within the specified workspace. Only owners and admins of the workspace can update channel names.
 * @summary Update the name of a channel
 */
export const updateChannelName = (
  workspaceId: string,
  channelId: string,
  updateChannelNameBody: UpdateChannelNameBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.patch(
    `/workspaces/${workspaceId}/channels/${channelId}`,
    updateChannelNameBody,
    options,
  );
};

export const getUpdateChannelNameMutationOptions = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateChannelName>>,
    TError,
    { workspaceId: string; channelId: string; data: UpdateChannelNameBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateChannelName>>,
  TError,
  { workspaceId: string; channelId: string; data: UpdateChannelNameBody },
  TContext
> => {
  const mutationKey = ["updateChannelName"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateChannelName>>,
    { workspaceId: string; channelId: string; data: UpdateChannelNameBody }
  > = (props) => {
    const { workspaceId, channelId, data } = props ?? {};

    return updateChannelName(workspaceId, channelId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateChannelNameMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateChannelName>>
>;
export type UpdateChannelNameMutationBody = UpdateChannelNameBody;
export type UpdateChannelNameMutationError = AxiosError<
  N400Response | N401Response | N403Response | N404Response
>;

/**
 * @summary Update the name of a channel
 */
export const useUpdateChannelName = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateChannelName>>,
    TError,
    { workspaceId: string; channelId: string; data: UpdateChannelNameBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateChannelName>>,
  TError,
  { workspaceId: string; channelId: string; data: UpdateChannelNameBody },
  TContext
> => {
  return useMutation(getUpdateChannelNameMutationOptions(options));
};
/**
 * Delete an existing channel from the specified workspace. Only owners and admins of the workspace can delete channels.
 * @summary Delete a channel from a workspace
 */
export const deleteChannel = (
  workspaceId: string,
  channelId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(
    `/workspaces/${workspaceId}/channels/${channelId}`,
    options,
  );
};

export const getDeleteChannelMutationOptions = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteChannel>>,
    TError,
    { workspaceId: string; channelId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteChannel>>,
  TError,
  { workspaceId: string; channelId: string },
  TContext
> => {
  const mutationKey = ["deleteChannel"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteChannel>>,
    { workspaceId: string; channelId: string }
  > = (props) => {
    const { workspaceId, channelId } = props ?? {};

    return deleteChannel(workspaceId, channelId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteChannelMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteChannel>>
>;

export type DeleteChannelMutationError = AxiosError<
  N400Response | N401Response | N403Response | N404Response
>;

/**
 * @summary Delete a channel from a workspace
 */
export const useDeleteChannel = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteChannel>>,
    TError,
    { workspaceId: string; channelId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteChannel>>,
  TError,
  { workspaceId: string; channelId: string },
  TContext
> => {
  return useMutation(getDeleteChannelMutationOptions(options));
};
