/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Create a new channel within the specified workspace. The user creating the channel will be added as a member of that channel. Only owners and admins of the workspace can create channels.
 * @summary Create a new channel in a workspace
 */
export const CreateChannelParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
});

export const CreateChannelBody = zod.object({
  name: zod.string().describe("The name of the channel"),
});

export const CreateChannelResponse = zod.void();

/**
 * Retrieve a list of all channels within the specified workspace.
 * @summary List all channels in a workspace
 */
export const ListChannelsParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
});

export const ListChannelsResponse = zod.object({
  channels: zod.array(
    zod.object({
      id: zod.string().describe("Unique identifier for the channel"),
      name: zod.string().describe("Name of the channel"),
      newMessagesCount: zod
        .number()
        .describe("Number of new messages in the channel"),
    }),
  ),
});

/**
 * Update the name of an existing channel within the specified workspace. Only owners and admins of the workspace can update channel names.
 * @summary Update the name of a channel
 */
export const UpdateChannelNameParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
});

export const UpdateChannelNameBody = zod.object({
  name: zod.string().describe("The new name of the channel"),
});

export const UpdateChannelNameResponse = zod.unknown();

/**
 * Delete an existing channel from the specified workspace. Only owners and admins of the workspace can delete channels.
 * @summary Delete a channel from a workspace
 */
export const DeleteChannelParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
  channelId: zod
    .string()
    .uuid()
    .describe("The unique identifier of the channel."),
});

export const DeleteChannelResponse = zod.unknown();
