/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Create a new workspace with the provided name and optional logo. The user creating the workspace will be set as the owner. To create workspace client need complete payment using returned Stripe Payment Intent client secret.
 * @summary Create a new workspace
 */
export const CreateWorkspaceBody = zod.object({
  workspaceName: zod.string(),
  workspaceLogo: zod
    .instanceof(File)
    .optional()
    .describe("Optional workspace logo image file"),
});

export const CreateWorkspaceResponse = zod.object({
  clientSecret: zod
    .string()
    .describe("Secret key generated by Stripe for processing the payment"),
});

/**
 * Retrieve a list of all workspaces that the authenticated user is a member of, including their roles within each workspace.
 * @summary List all workspaces the user is a member of
 */
export const ListWorkspacesResponse = zod.object({
  workspaces: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      logoUrl: zod.string().url(),
      userRole: zod
        .enum(["owner", "admin", "member"])
        .describe("The role of the authenticated user within the workspace"),
      channels: zod
        .array(
          zod.object({
            id: zod.string().describe("Unique identifier for the channel"),
            name: zod.string().describe("Name of the channel"),
            newMessagesCount: zod
              .number()
              .describe("Number of new messages in the channel"),
          }),
        )
        .describe("List of channels within the workspace"),
      users: zod
        .array(
          zod.object({
            id: zod.string().describe("Unique identifier for the user"),
            name: zod.string().describe("Name of the user"),
            surname: zod.string().describe("Surname of the user"),
            email: zod.string().describe("Email address of the user"),
            avatarUrl: zod.string().describe("URL of the user's avatar image"),
            status: zod.enum([
              "online",
              "meeting",
              "vacation",
              "notDisturb",
              "workAtHome",
              "freeTime",
              "offline",
            ]),
          }),
        )
        .describe("List of users who are members of the workspace"),
    }),
  ),
});

/**
 * Confirm the Stripe Payment Intent for workspace creation. This endpoint should be called after the client completes the payment process using the client secret provided in the response of the workspace creation endpoint.
 * @summary Accept payment for workspace creation
 */
export const AcceptWorkspacePaymentBody = zod.object({
  paymentIntentId: zod
    .string()
    .describe("ID of the Stripe Payment Intent to confirm"),
});

export const AcceptWorkspacePaymentResponse = zod.unknown();

/**
 * Update the logo of an existing workspace. Only the workspace owner can update the logo.
 * @summary Update workspace logo
 */
export const UpdateWorkspaceLogoParams = zod.object({
  workspaceId: zod.string().uuid().describe("The ID of the workspace."),
});

export const UpdateWorkspaceLogoBody = zod.object({
  workspaceLogo: zod.instanceof(File).describe("New workspace logo image file"),
});

export const UpdateWorkspaceLogoResponse = zod.unknown();
