/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptPaymentRequestBody,
  CreatePaymentResponseResponse,
  CreateWorkspaceRequestBody,
  N400Response,
  N401Response,
  N402Response,
  N403Response,
  N404Response,
  UpdateWorkspaceLogoRequestBody,
  WorkspaceListResponseResponse
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type createWorkspaceResponse201 = {
  data: CreatePaymentResponseResponse
  status: 201
}

export type createWorkspaceResponse400 = {
  data: N400Response
  status: 400
}

export type createWorkspaceResponse401 = {
  data: N401Response
  status: 401
}

export type createWorkspaceResponseSuccess = (createWorkspaceResponse201) & {
  headers: Headers;
};
export type createWorkspaceResponseError = (createWorkspaceResponse400 | createWorkspaceResponse401) & {
  headers: Headers;
};

export type createWorkspaceResponse = (createWorkspaceResponseSuccess | createWorkspaceResponseError)

export const getCreateWorkspaceUrl = () => {




  return `/workspaces`
}

/**
 * Create a new workspace with the provided name and optional logo. The user creating the workspace will be set as the owner. To create workspace client need complete payment using returned Stripe Payment Intent client secret.
 * @summary Create a new workspace
 */
export const createWorkspace = async (createWorkspaceRequestBody?: CreateWorkspaceRequestBody, options?: RequestInit): Promise<createWorkspaceResponse> => {
    const formData = new FormData();
if(createWorkspaceRequestBody?.workspaceName !== undefined) {
 formData.append(`workspaceName`, createWorkspaceRequestBody.workspaceName);
 }
if(createWorkspaceRequestBody?.workspaceLogo !== undefined) {
 formData.append(`workspaceLogo`, createWorkspaceRequestBody.workspaceLogo);
 }

  const res = await fetch(getCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createWorkspaceResponse
}




export const getCreateWorkspaceMutationOptions = <TError = N400Response | N401Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data?: CreateWorkspaceRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data?: CreateWorkspaceRequestBody}, TContext> => {

const mutationKey = ['createWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkspace>>, {data?: CreateWorkspaceRequestBody}> = (props) => {
          const {data} = props ?? {};

          return  createWorkspace(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspace>>>
    export type CreateWorkspaceMutationBody = CreateWorkspaceRequestBody | undefined
    export type CreateWorkspaceMutationError = N400Response | N401Response

    /**
 * @summary Create a new workspace
 */
export const useCreateWorkspace = <TError = N400Response | N401Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data?: CreateWorkspaceRequestBody}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createWorkspace>>,
        TError,
        {data?: CreateWorkspaceRequestBody},
        TContext
      > => {
      return useMutation(getCreateWorkspaceMutationOptions(options));
    }
    export type listWorkspacesResponse200 = {
  data: WorkspaceListResponseResponse
  status: 200
}

export type listWorkspacesResponse401 = {
  data: N401Response
  status: 401
}

export type listWorkspacesResponseSuccess = (listWorkspacesResponse200) & {
  headers: Headers;
};
export type listWorkspacesResponseError = (listWorkspacesResponse401) & {
  headers: Headers;
};

export type listWorkspacesResponse = (listWorkspacesResponseSuccess | listWorkspacesResponseError)

export const getListWorkspacesUrl = () => {




  return `/workspaces`
}

/**
 * Retrieve a list of all workspaces that the authenticated user is a member of, including their roles within each workspace.
 * @summary List all workspaces the user is a member of
 */
export const listWorkspaces = async ( options?: RequestInit): Promise<listWorkspacesResponse> => {

  const res = await fetch(getListWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listWorkspacesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listWorkspacesResponse
}





export const getListWorkspacesQueryKey = () => {
    return [
    `/workspaces`
    ] as const;
    }


export const getListWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = N401Response>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkspacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkspaces>>> = ({ signal }) => listWorkspaces({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData> & { queryKey: QueryKey }
}

export type ListWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkspaces>>>
export type ListWorkspacesQueryError = N401Response


/**
 * @summary List all workspaces the user is a member of
 */

export function useListWorkspaces<TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = N401Response>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListWorkspacesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type acceptWorkspacePaymentResponse200 = {
  data: void
  status: 200
}

export type acceptWorkspacePaymentResponse400 = {
  data: N400Response
  status: 400
}

export type acceptWorkspacePaymentResponse401 = {
  data: N401Response
  status: 401
}

export type acceptWorkspacePaymentResponse402 = {
  data: N402Response
  status: 402
}

export type acceptWorkspacePaymentResponseSuccess = (acceptWorkspacePaymentResponse200) & {
  headers: Headers;
};
export type acceptWorkspacePaymentResponseError = (acceptWorkspacePaymentResponse400 | acceptWorkspacePaymentResponse401 | acceptWorkspacePaymentResponse402) & {
  headers: Headers;
};

export type acceptWorkspacePaymentResponse = (acceptWorkspacePaymentResponseSuccess | acceptWorkspacePaymentResponseError)

export const getAcceptWorkspacePaymentUrl = () => {




  return `/workspaces/accept-payment`
}

/**
 * Confirm the Stripe Payment Intent for workspace creation. This endpoint should be called after the client completes the payment process using the client secret provided in the response of the workspace creation endpoint.
 * @summary Accept payment for workspace creation
 */
export const acceptWorkspacePayment = async (acceptPaymentRequestBody?: AcceptPaymentRequestBody, options?: RequestInit): Promise<acceptWorkspacePaymentResponse> => {

  const res = await fetch(getAcceptWorkspacePaymentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(acceptPaymentRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: acceptWorkspacePaymentResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as acceptWorkspacePaymentResponse
}




export const getAcceptWorkspacePaymentMutationOptions = <TError = N400Response | N401Response | N402Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptWorkspacePayment>>, TError,{data?: AcceptPaymentRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof acceptWorkspacePayment>>, TError,{data?: AcceptPaymentRequestBody}, TContext> => {

const mutationKey = ['acceptWorkspacePayment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptWorkspacePayment>>, {data?: AcceptPaymentRequestBody}> = (props) => {
          const {data} = props ?? {};

          return  acceptWorkspacePayment(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptWorkspacePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof acceptWorkspacePayment>>>
    export type AcceptWorkspacePaymentMutationBody = AcceptPaymentRequestBody | undefined
    export type AcceptWorkspacePaymentMutationError = N400Response | N401Response | N402Response

    /**
 * @summary Accept payment for workspace creation
 */
export const useAcceptWorkspacePayment = <TError = N400Response | N401Response | N402Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptWorkspacePayment>>, TError,{data?: AcceptPaymentRequestBody}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof acceptWorkspacePayment>>,
        TError,
        {data?: AcceptPaymentRequestBody},
        TContext
      > => {
      return useMutation(getAcceptWorkspacePaymentMutationOptions(options));
    }
    export type updateWorkspaceLogoResponse200 = {
  data: void
  status: 200
}

export type updateWorkspaceLogoResponse400 = {
  data: N400Response
  status: 400
}

export type updateWorkspaceLogoResponse401 = {
  data: N401Response
  status: 401
}

export type updateWorkspaceLogoResponse403 = {
  data: N403Response
  status: 403
}

export type updateWorkspaceLogoResponse404 = {
  data: N404Response
  status: 404
}

export type updateWorkspaceLogoResponseSuccess = (updateWorkspaceLogoResponse200) & {
  headers: Headers;
};
export type updateWorkspaceLogoResponseError = (updateWorkspaceLogoResponse400 | updateWorkspaceLogoResponse401 | updateWorkspaceLogoResponse403 | updateWorkspaceLogoResponse404) & {
  headers: Headers;
};

export type updateWorkspaceLogoResponse = (updateWorkspaceLogoResponseSuccess | updateWorkspaceLogoResponseError)

export const getUpdateWorkspaceLogoUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}`
}

/**
 * Update the logo of an existing workspace. Only the workspace owner can update the logo.
 * @summary Update workspace logo
 */
export const updateWorkspaceLogo = async (workspaceId: string,
    updateWorkspaceLogoRequestBody?: UpdateWorkspaceLogoRequestBody, options?: RequestInit): Promise<updateWorkspaceLogoResponse> => {
    const formData = new FormData();
if(updateWorkspaceLogoRequestBody?.workspaceLogo !== undefined) {
 formData.append(`workspaceLogo`, updateWorkspaceLogoRequestBody.workspaceLogo);
 }

  const res = await fetch(getUpdateWorkspaceLogoUrl(workspaceId),
  {
    ...options,
    method: 'PATCH'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateWorkspaceLogoResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as updateWorkspaceLogoResponse
}




export const getUpdateWorkspaceLogoMutationOptions = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkspaceLogo>>, TError,{workspaceId: string;data?: UpdateWorkspaceLogoRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkspaceLogo>>, TError,{workspaceId: string;data?: UpdateWorkspaceLogoRequestBody}, TContext> => {

const mutationKey = ['updateWorkspaceLogo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkspaceLogo>>, {workspaceId: string;data?: UpdateWorkspaceLogoRequestBody}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  updateWorkspaceLogo(workspaceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkspaceLogoMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkspaceLogo>>>
    export type UpdateWorkspaceLogoMutationBody = UpdateWorkspaceLogoRequestBody | undefined
    export type UpdateWorkspaceLogoMutationError = N400Response | N401Response | N403Response | N404Response

    /**
 * @summary Update workspace logo
 */
export const useUpdateWorkspaceLogo = <TError = N400Response | N401Response | N403Response | N404Response,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkspaceLogo>>, TError,{workspaceId: string;data?: UpdateWorkspaceLogoRequestBody}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateWorkspaceLogo>>,
        TError,
        {workspaceId: string;data?: UpdateWorkspaceLogoRequestBody},
        TContext
      > => {
      return useMutation(getUpdateWorkspaceLogoMutationOptions(options));
    }
