/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
  CreatePaymentResponse,
  WorkspaceListResponse,
} from "../../models";

export const getCreateWorkspaceResponseMock = (
  overrideResponse: Partial<Extract<CreatePaymentResponse, object>> = {},
): CreatePaymentResponse => ({
  clientSecret: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getListWorkspacesResponseMock = (
  overrideResponse: Partial<Extract<WorkspaceListResponse, object>> = {},
): WorkspaceListResponse => ({
  workspaces: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    logoUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
    userRole: faker.helpers.arrayElement(["owner", "admin", "member"] as const),
    channels: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      newMessagesCount: faker.number.int(),
    })),
    users: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      surname: faker.string.alpha({ length: { min: 10, max: 20 } }),
      email: faker.string.alpha({ length: { min: 10, max: 20 } }),
      avatarUrl: faker.string.alpha({ length: { min: 10, max: 20 } }),
      status: faker.helpers.arrayElement([
        "online",
        "meeting",
        "vacations",
        "notDisturb",
        "workAtHome",
        "freeTime",
        "offline",
      ] as const),
      workspaceRole: faker.helpers.arrayElement([
        faker.helpers.arrayElement(["owner", "admin", "member"] as const),
        undefined,
      ]),
    })),
  })),
  ...overrideResponse,
});
