/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CreateDirectChatBody,
  DirectChat,
  DirectChatListResponse,
  N400Response,
  N401Response,
  N403Response,
  N404Response,
} from "../../models";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Retrieve a list of all direct chats that the authenticated user is a part of within the specified workspace.
 * @summary List all direct chats in a workspace
 */
export const listDirectChats = (
  workspaceId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DirectChatListResponse>> => {
  return axios.get(`/workspaces/${workspaceId}/direct-chats`, options);
};

export const getListDirectChatsQueryKey = (workspaceId: string) => {
  return [`/workspaces/${workspaceId}/direct-chats`] as const;
};

export const getListDirectChatsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDirectChats>>,
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDirectChats>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListDirectChatsQueryKey(workspaceId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDirectChats>>> = ({
    signal,
  }) => listDirectChats(workspaceId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: workspaceId !== null && workspaceId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listDirectChats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDirectChatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDirectChats>>
>;
export type ListDirectChatsQueryError = AxiosError<
  N400Response | N401Response | N403Response | N404Response
>;

/**
 * @summary List all direct chats in a workspace
 */

export function useListDirectChats<
  TData = Awaited<ReturnType<typeof listDirectChats>>,
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
>(
  workspaceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDirectChats>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDirectChatsQueryOptions(workspaceId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns the existing direct chat with the given user in the workspace, creating it if none exists.
 * @summary Open or create a direct chat with another user
 */
export const createDirectChat = (
  workspaceId: string,
  createDirectChatBody: CreateDirectChatBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DirectChat>> => {
  return axios.post(
    `/workspaces/${workspaceId}/direct-chats`,
    createDirectChatBody,
    options,
  );
};

export const getCreateDirectChatMutationOptions = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDirectChat>>,
    TError,
    { workspaceId: string; data: CreateDirectChatBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDirectChat>>,
  TError,
  { workspaceId: string; data: CreateDirectChatBody },
  TContext
> => {
  const mutationKey = ["createDirectChat"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDirectChat>>,
    { workspaceId: string; data: CreateDirectChatBody }
  > = (props) => {
    const { workspaceId, data } = props ?? {};

    return createDirectChat(workspaceId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDirectChatMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDirectChat>>
>;
export type CreateDirectChatMutationBody = CreateDirectChatBody;
export type CreateDirectChatMutationError = AxiosError<
  N400Response | N401Response | N403Response | N404Response
>;

/**
 * @summary Open or create a direct chat with another user
 */
export const useCreateDirectChat = <
  TError = AxiosError<
    N400Response | N401Response | N403Response | N404Response
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDirectChat>>,
    TError,
    { workspaceId: string; data: CreateDirectChatBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof createDirectChat>>,
  TError,
  { workspaceId: string; data: CreateDirectChatBody },
  TContext
> => {
  return useMutation(getCreateDirectChatMutationOptions(options));
};
/**
 * Marks the direct chat as read for the authenticated user, clearing its unread message count.
 * @summary Mark a direct chat as read
 */
export const markDirectChatRead = (
  workspaceId: string,
  directChatId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/workspaces/${workspaceId}/direct-chats/${directChatId}/read`,
    undefined,
    options,
  );
};

export const getMarkDirectChatReadMutationOptions = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markDirectChatRead>>,
    TError,
    { workspaceId: string; directChatId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markDirectChatRead>>,
  TError,
  { workspaceId: string; directChatId: string },
  TContext
> => {
  const mutationKey = ["markDirectChatRead"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markDirectChatRead>>,
    { workspaceId: string; directChatId: string }
  > = (props) => {
    const { workspaceId, directChatId } = props ?? {};

    return markDirectChatRead(workspaceId, directChatId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkDirectChatReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof markDirectChatRead>>
>;

export type MarkDirectChatReadMutationError = AxiosError<
  N401Response | N403Response | N404Response
>;

/**
 * @summary Mark a direct chat as read
 */
export const useMarkDirectChatRead = <
  TError = AxiosError<N401Response | N403Response | N404Response>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markDirectChatRead>>,
    TError,
    { workspaceId: string; directChatId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof markDirectChatRead>>,
  TError,
  { workspaceId: string; directChatId: string },
  TContext
> => {
  return useMutation(getMarkDirectChatReadMutationOptions(options));
};
