/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DirectChatListResponseResponse,
  N400Response,
  N401Response,
  N403Response,
  N404Response
} from '../../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type listDirectChatsResponse200 = {
  data: DirectChatListResponseResponse
  status: 200
}

export type listDirectChatsResponse400 = {
  data: N400Response
  status: 400
}

export type listDirectChatsResponse401 = {
  data: N401Response
  status: 401
}

export type listDirectChatsResponse403 = {
  data: N403Response
  status: 403
}

export type listDirectChatsResponse404 = {
  data: N404Response
  status: 404
}

export type listDirectChatsResponseSuccess = (listDirectChatsResponse200) & {
  headers: Headers;
};
export type listDirectChatsResponseError = (listDirectChatsResponse400 | listDirectChatsResponse401 | listDirectChatsResponse403 | listDirectChatsResponse404) & {
  headers: Headers;
};

export type listDirectChatsResponse = (listDirectChatsResponseSuccess | listDirectChatsResponseError)

export const getListDirectChatsUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}/direct-chats`
}

/**
 * Retrieve a list of all direct chats that the authenticated user is a part of within the specified workspace.
 * @summary List all direct chats in a workspace
 */
export const listDirectChats = async (workspaceId: string, options?: RequestInit): Promise<listDirectChatsResponse> => {

  const res = await fetch(getListDirectChatsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listDirectChatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listDirectChatsResponse
}





export const getListDirectChatsQueryKey = (workspaceId: string,) => {
    return [
    `/workspaces/${workspaceId}/direct-chats`
    ] as const;
    }


export const getListDirectChatsQueryOptions = <TData = Awaited<ReturnType<typeof listDirectChats>>, TError = N400Response | N401Response | N403Response | N404Response>(workspaceId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDirectChats>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDirectChatsQueryKey(workspaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDirectChats>>> = ({ signal }) => listDirectChats(workspaceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: workspaceId !== null && workspaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDirectChats>>, TError, TData> & { queryKey: QueryKey }
}

export type ListDirectChatsQueryResult = NonNullable<Awaited<ReturnType<typeof listDirectChats>>>
export type ListDirectChatsQueryError = N400Response | N401Response | N403Response | N404Response


/**
 * @summary List all direct chats in a workspace
 */

export function useListDirectChats<TData = Awaited<ReturnType<typeof listDirectChats>>, TError = N400Response | N401Response | N403Response | N404Response>(
 workspaceId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDirectChats>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListDirectChatsQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






