/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Szponcik communicator API
 * OpenAPI spec version: 0.0.1
 */
import {
  faker
} from '@faker-js/faker';

import type {
  DirectChatListResponseResponse
} from '../../models';


export const getListDirectChatsResponseMock = (overrideResponse: Partial<Extract<DirectChatListResponseResponse, object>> = {}): DirectChatListResponseResponse => ({directChats: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), participant: {id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), surname: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), avatarUrl: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(['online','meeting','vacation','notDisturb','workAtHome','freeTime','offline'] as const)}, newMessagesCount: faker.number.int()})), ...overrideResponse})

