name: Generate OpenAPI Schemas and Documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/openapi-generator.yml'
      - 'shared/openapi/**'
      - 'shared/generators/orval/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: openapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-schemas-and-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Node tools
        run: npm install -g @redocly/cli orval prettier

      - name: Install orval for schema directory
        working-directory: shared/generators/orval
        run: npm install

      - name: Generate orval api
        working-directory: shared/generators/orval
        run: orval --config orval.config.ts

      - name: Generate redocly docs
        run: redocly build-docs shared/openapi/openapi.yaml --output docs/openapi/index.html

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update OpenAPI documentation"
          file_pattern: 'docs/openapi/* app/src/api/*'